/* ============================================================
 * 手機／平板型號  js/data-phones.js
 * 欄位：n 型號  b 品牌  soc 晶片（須與 data-hardware.js 的 SOCS 名稱一致）
 *       ram 常見記憶體規格（GB）  os 'ios' | 'android'
 * 以台灣販售版本為準（例如 S22 為 Snapdragon、S24 為 Exynos）。
 * ============================================================ */
const PHONES=[
  // ── 品牌：Apple
  {n:'iPhone 17 Pro / 17 Pro Max',b:'Apple',soc:'Apple A19 Pro',ram:[12],os:'ios'},
  {n:'iPhone Air',b:'Apple',soc:'Apple A19 Pro',ram:[12],os:'ios'},
  {n:'iPhone 17',b:'Apple',soc:'Apple A19',ram:[8],os:'ios'},
  {n:'iPhone 16e',b:'Apple',soc:'Apple A18',ram:[8],os:'ios'},
  {n:'iPhone 16 Pro / 16 Pro Max',b:'Apple',soc:'Apple A18 Pro',ram:[8],os:'ios'},
  {n:'iPhone 16 / 16 Plus',b:'Apple',soc:'Apple A18',ram:[8],os:'ios'},
  {n:'iPhone 15 Pro / 15 Pro Max',b:'Apple',soc:'Apple A17 Pro',ram:[8],os:'ios'},
  {n:'iPhone 15 / 15 Plus',b:'Apple',soc:'Apple A16 Bionic',ram:[6],os:'ios'},
  {n:'iPhone 14 Pro / 14 Pro Max',b:'Apple',soc:'Apple A16 Bionic',ram:[6],os:'ios'},
  {n:'iPhone 14 / 14 Plus',b:'Apple',soc:'Apple A15 Bionic',ram:[6],os:'ios'},
  {n:'iPhone 13 Pro / 13 Pro Max',b:'Apple',soc:'Apple A15 Bionic',ram:[6],os:'ios'},
  {n:'iPhone 13 / 13 mini',b:'Apple',soc:'Apple A15 Bionic',ram:[4],os:'ios'},
  {n:'iPhone SE（第 3 代）',b:'Apple',soc:'Apple A15 Bionic',ram:[4],os:'ios'},
  {n:'iPhone 12 Pro / 12 Pro Max',b:'Apple',soc:'Apple A14 Bionic',ram:[6],os:'ios'},
  {n:'iPhone 12 / 12 mini',b:'Apple',soc:'Apple A14 Bionic',ram:[4],os:'ios'},
  {n:'iPhone 11 Pro / 11 Pro Max',b:'Apple',soc:'Apple A13 Bionic',ram:[4],os:'ios'},
  {n:'iPhone 11',b:'Apple',soc:'Apple A13 Bionic',ram:[4],os:'ios'},
  {n:'iPhone SE（第 2 代）',b:'Apple',soc:'Apple A13 Bionic',ram:[3],os:'ios'},
  {n:'iPhone XS / XS Max',b:'Apple',soc:'Apple A12 Bionic',ram:[4],os:'ios'},
  {n:'iPhone XR',b:'Apple',soc:'Apple A12 Bionic',ram:[3],os:'ios'},
  {n:'iPhone X',b:'Apple',soc:'Apple A11 Bionic',ram:[3],os:'ios'},
  {n:'iPhone 8 Plus',b:'Apple',soc:'Apple A11 Bionic',ram:[3],os:'ios'},
  {n:'iPhone 8',b:'Apple',soc:'Apple A11 Bionic',ram:[2],os:'ios'},
  {n:'iPhone 7 / 7 Plus',b:'Apple',soc:'Apple A10 Fusion',ram:[2,3],os:'ios'},
  {n:'iPhone 6s / 6s Plus',b:'Apple',soc:'Apple A9',ram:[2],os:'ios'},
  {n:'iPad Pro（M5）',b:'Apple',soc:'Apple M5',ram:[12,16],os:'ios'},
  {n:'iPad Pro（M4）',b:'Apple',soc:'Apple M4',ram:[8,16],os:'ios'},
  {n:'iPad Air（M3）',b:'Apple',soc:'Apple M3',ram:[8],os:'ios'},
  {n:'iPad Air（M2）',b:'Apple',soc:'Apple M2',ram:[8],os:'ios'},
  {n:'iPad Air（第 5 代，M1）',b:'Apple',soc:'Apple M1',ram:[8],os:'ios'},
  {n:'iPad Air（第 4 代）',b:'Apple',soc:'Apple A14 Bionic',ram:[4],os:'ios'},
  {n:'iPad mini（A17 Pro）',b:'Apple',soc:'Apple A17 Pro',ram:[8],os:'ios'},
  {n:'iPad mini（第 6 代）',b:'Apple',soc:'Apple A15 Bionic',ram:[4],os:'ios'},
  {n:'iPad（A16）',b:'Apple',soc:'Apple A16 Bionic',ram:[6],os:'ios'},
  {n:'iPad（第 10 代）',b:'Apple',soc:'Apple A14 Bionic',ram:[4],os:'ios'},
  {n:'iPad（第 9 代）',b:'Apple',soc:'Apple A13 Bionic',ram:[3],os:'ios'},
  {n:'iPad（第 8 代）',b:'Apple',soc:'Apple A12 Bionic',ram:[3],os:'ios'},
  // ── 品牌：Samsung
  {n:'Galaxy S25 Ultra',b:'Samsung',soc:'Snapdragon 8 Elite',ram:[12,16],os:'android'},
  {n:'Galaxy S25 / S25+',b:'Samsung',soc:'Snapdragon 8 Elite',ram:[12],os:'android'},
  {n:'Galaxy S25 Edge',b:'Samsung',soc:'Snapdragon 8 Elite',ram:[12],os:'android'},
  {n:'Galaxy S25 FE',b:'Samsung',soc:'Exynos 2400',ram:[8],os:'android'},
  {n:'Galaxy S24 Ultra',b:'Samsung',soc:'Snapdragon 8 Gen 3',ram:[12],os:'android'},
  {n:'Galaxy S24 / S24+',b:'Samsung',soc:'Exynos 2400',ram:[8,12],os:'android'},
  {n:'Galaxy S24 FE',b:'Samsung',soc:'Exynos 2400e',ram:[8],os:'android'},
  {n:'Galaxy S23 Ultra',b:'Samsung',soc:'Snapdragon 8 Gen 2',ram:[12],os:'android'},
  {n:'Galaxy S23 / S23+',b:'Samsung',soc:'Snapdragon 8 Gen 2',ram:[8],os:'android'},
  {n:'Galaxy S23 FE',b:'Samsung',soc:'Exynos 2200',ram:[8],os:'android'},
  {n:'Galaxy S22 / S22+ / S22 Ultra',b:'Samsung',soc:'Snapdragon 8 Gen 1',ram:[8,12],os:'android'},
  {n:'Galaxy S21 / S21+ / S21 Ultra',b:'Samsung',soc:'Exynos 2100',ram:[8,12],os:'android'},
  {n:'Galaxy S21 FE',b:'Samsung',soc:'Snapdragon 888',ram:[6,8],os:'android'},
  {n:'Galaxy S20 / S20+ / S20 Ultra',b:'Samsung',soc:'Exynos 990',ram:[8,12],os:'android'},
  {n:'Galaxy S20 FE',b:'Samsung',soc:'Snapdragon 865',ram:[6,8],os:'android'},
  {n:'Galaxy S10 / S10+',b:'Samsung',soc:'Exynos 9820',ram:[8],os:'android'},
  {n:'Galaxy Z Fold7',b:'Samsung',soc:'Snapdragon 8 Elite',ram:[12,16],os:'android'},
  {n:'Galaxy Z Flip7',b:'Samsung',soc:'Exynos 2500',ram:[12],os:'android'},
  {n:'Galaxy Z Flip7 FE',b:'Samsung',soc:'Exynos 2400',ram:[8],os:'android'},
  {n:'Galaxy Z Fold6 / Flip6',b:'Samsung',soc:'Snapdragon 8 Gen 3',ram:[12],os:'android'},
  {n:'Galaxy Z Fold5 / Flip5',b:'Samsung',soc:'Snapdragon 8 Gen 2',ram:[8,12],os:'android'},
  {n:'Galaxy Z Fold4 / Flip4',b:'Samsung',soc:'Snapdragon 8+ Gen 1',ram:[8,12],os:'android'},
  {n:'Galaxy A56',b:'Samsung',soc:'Exynos 1580',ram:[8,12],os:'android'},
  {n:'Galaxy A36',b:'Samsung',soc:'Snapdragon 6 Gen 1',ram:[8],os:'android'},
  {n:'Galaxy A26',b:'Samsung',soc:'Exynos 1380',ram:[8],os:'android'},
  {n:'Galaxy A17 5G',b:'Samsung',soc:'Exynos 1330',ram:[6,8],os:'android'},
  {n:'Galaxy A16 5G',b:'Samsung',soc:'Exynos 1330',ram:[4,8],os:'android'},
  {n:'Galaxy A07',b:'Samsung',soc:'Helio G99',ram:[4,6],os:'android'},
  {n:'Galaxy A55',b:'Samsung',soc:'Exynos 1480',ram:[8,12],os:'android'},
  {n:'Galaxy A35',b:'Samsung',soc:'Exynos 1380',ram:[8],os:'android'},
  {n:'Galaxy A25',b:'Samsung',soc:'Exynos 1280',ram:[8],os:'android'},
  {n:'Galaxy A15 5G',b:'Samsung',soc:'Dimensity 6100+',ram:[4,8],os:'android'},
  {n:'Galaxy A06',b:'Samsung',soc:'Helio G85',ram:[4,6],os:'android'},
  {n:'Galaxy A54',b:'Samsung',soc:'Exynos 1380',ram:[8],os:'android'},
  {n:'Galaxy A34',b:'Samsung',soc:'Dimensity 1080',ram:[8],os:'android'},
  {n:'Galaxy A14 5G',b:'Samsung',soc:'Exynos 1330',ram:[4,6],os:'android'},
  {n:'Galaxy A53',b:'Samsung',soc:'Exynos 1280',ram:[8],os:'android'},
  {n:'Galaxy A33',b:'Samsung',soc:'Exynos 1280',ram:[6,8],os:'android'},
  {n:'Galaxy A52s',b:'Samsung',soc:'Snapdragon 778G',ram:[8],os:'android'},
  {n:'Galaxy M55',b:'Samsung',soc:'Snapdragon 7 Gen 1',ram:[8],os:'android'},
  {n:'Galaxy M15 5G',b:'Samsung',soc:'Dimensity 6100+',ram:[4,6],os:'android'},
  {n:'Galaxy Tab S11 / S11 Ultra',b:'Samsung',soc:'Dimensity 9400+',ram:[12],os:'android'},
  {n:'Galaxy Tab S10+ / S10 Ultra',b:'Samsung',soc:'Dimensity 9300+',ram:[12],os:'android'},
  {n:'Galaxy Tab S10 FE',b:'Samsung',soc:'Exynos 1580',ram:[8],os:'android'},
  {n:'Galaxy Tab S9 / S9+ / S9 Ultra',b:'Samsung',soc:'Snapdragon 8 Gen 2',ram:[8,12],os:'android'},
  {n:'Galaxy Tab S9 FE',b:'Samsung',soc:'Exynos 1380',ram:[6,8],os:'android'},
  {n:'Galaxy Tab A9+',b:'Samsung',soc:'Snapdragon 695',ram:[4,8],os:'android'},
  // ── 品牌：Google
  {n:'Pixel 10 / 10 Pro / 10 Pro XL',b:'Google',soc:'Google Tensor G5',ram:[12,16],os:'android'},
  {n:'Pixel 10 Pro Fold',b:'Google',soc:'Google Tensor G5',ram:[16],os:'android'},
  {n:'Pixel 9a',b:'Google',soc:'Google Tensor G4',ram:[8],os:'android'},
  {n:'Pixel 9 / 9 Pro / 9 Pro XL',b:'Google',soc:'Google Tensor G4',ram:[12,16],os:'android'},
  {n:'Pixel 8a',b:'Google',soc:'Google Tensor G3',ram:[8],os:'android'},
  {n:'Pixel 8 / 8 Pro',b:'Google',soc:'Google Tensor G3',ram:[8,12],os:'android'},
  {n:'Pixel 7a',b:'Google',soc:'Google Tensor G2',ram:[8],os:'android'},
  {n:'Pixel 7 / 7 Pro',b:'Google',soc:'Google Tensor G2',ram:[8,12],os:'android'},
  {n:'Pixel 6a',b:'Google',soc:'Google Tensor',ram:[6],os:'android'},
  {n:'Pixel 6 / 6 Pro',b:'Google',soc:'Google Tensor',ram:[8,12],os:'android'},
  // ── 品牌：Xiaomi
  {n:'Xiaomi 17 / 17 Pro / 17 Pro Max',b:'Xiaomi',soc:'Snapdragon 8 Elite Gen 5',ram:[12,16],os:'android'},
  {n:'Xiaomi 15 / 15 Pro',b:'Xiaomi',soc:'Snapdragon 8 Elite',ram:[12,16],os:'android'},
  {n:'Xiaomi 15 Ultra',b:'Xiaomi',soc:'Snapdragon 8 Elite',ram:[16],os:'android'},
  {n:'Xiaomi 15T Pro',b:'Xiaomi',soc:'Dimensity 9400+',ram:[12],os:'android'},
  {n:'Xiaomi 15T',b:'Xiaomi',soc:'Dimensity 8400',ram:[12],os:'android'},
  {n:'Xiaomi 14 / 14 Pro / 14 Ultra',b:'Xiaomi',soc:'Snapdragon 8 Gen 3',ram:[12,16],os:'android'},
  {n:'Xiaomi 14T Pro',b:'Xiaomi',soc:'Dimensity 9300+',ram:[12],os:'android'},
  {n:'Xiaomi 14T',b:'Xiaomi',soc:'Dimensity 8300',ram:[12],os:'android'},
  {n:'Xiaomi 13 / 13 Pro',b:'Xiaomi',soc:'Snapdragon 8 Gen 2',ram:[8,12],os:'android'},
  {n:'Xiaomi 13T Pro',b:'Xiaomi',soc:'Dimensity 9200+',ram:[12],os:'android'},
  {n:'Xiaomi 13T',b:'Xiaomi',soc:'Dimensity 8200',ram:[8,12],os:'android'},
  {n:'Xiaomi 12 / 12 Pro',b:'Xiaomi',soc:'Snapdragon 8 Gen 1',ram:[8,12],os:'android'},
  {n:'Xiaomi 12T Pro',b:'Xiaomi',soc:'Snapdragon 8+ Gen 1',ram:[8,12],os:'android'},
  {n:'Xiaomi 12T',b:'Xiaomi',soc:'Dimensity 8100',ram:[8],os:'android'},
  {n:'Xiaomi 11T Pro',b:'Xiaomi',soc:'Snapdragon 888',ram:[8],os:'android'},
  {n:'Redmi Note 14 Pro+ 5G',b:'Xiaomi',soc:'Snapdragon 7s Gen 3',ram:[8,12],os:'android'},
  {n:'Redmi Note 14 Pro 5G',b:'Xiaomi',soc:'Dimensity 7300',ram:[8],os:'android'},
  {n:'Redmi Note 14 5G',b:'Xiaomi',soc:'Dimensity 7025',ram:[6,8],os:'android'},
  {n:'Redmi Note 14（4G）',b:'Xiaomi',soc:'Helio G99',ram:[6,8],os:'android'},
  {n:'Redmi Note 13 Pro+ 5G',b:'Xiaomi',soc:'Dimensity 7200',ram:[8,12],os:'android'},
  {n:'Redmi Note 13 Pro 5G',b:'Xiaomi',soc:'Snapdragon 7s Gen 2',ram:[8],os:'android'},
  {n:'Redmi Note 13 5G',b:'Xiaomi',soc:'Dimensity 6080',ram:[6,8],os:'android'},
  {n:'Redmi Note 13（4G）',b:'Xiaomi',soc:'Snapdragon 685',ram:[6,8],os:'android'},
  {n:'Redmi Note 12 Pro 5G',b:'Xiaomi',soc:'Dimensity 1080',ram:[6,8],os:'android'},
  {n:'Redmi Note 12 5G',b:'Xiaomi',soc:'Snapdragon 4 Gen 1',ram:[4,6],os:'android'},
  {n:'Redmi 15 5G',b:'Xiaomi',soc:'Snapdragon 6s Gen 3',ram:[6,8],os:'android'},
  {n:'Redmi 14C',b:'Xiaomi',soc:'Helio G81',ram:[4,8],os:'android'},
  {n:'Redmi 13',b:'Xiaomi',soc:'Helio G91',ram:[6,8],os:'android'},
  {n:'Redmi 13C',b:'Xiaomi',soc:'Helio G85',ram:[4,8],os:'android'},
  {n:'POCO F7 Ultra',b:'Xiaomi',soc:'Snapdragon 8 Elite',ram:[12,16],os:'android'},
  {n:'POCO F7 Pro',b:'Xiaomi',soc:'Snapdragon 8 Gen 3',ram:[12],os:'android'},
  {n:'POCO F7',b:'Xiaomi',soc:'Snapdragon 8s Gen 4',ram:[12],os:'android'},
  {n:'POCO F6 Pro',b:'Xiaomi',soc:'Snapdragon 8 Gen 2',ram:[12],os:'android'},
  {n:'POCO F6',b:'Xiaomi',soc:'Snapdragon 8s Gen 3',ram:[8,12],os:'android'},
  {n:'POCO X7 Pro',b:'Xiaomi',soc:'Dimensity 8400',ram:[8,12],os:'android'},
  {n:'POCO X7',b:'Xiaomi',soc:'Dimensity 7300',ram:[8],os:'android'},
  {n:'POCO X6 Pro',b:'Xiaomi',soc:'Dimensity 8300',ram:[8,12],os:'android'},
  {n:'POCO X6',b:'Xiaomi',soc:'Snapdragon 7s Gen 2',ram:[8,12],os:'android'},
  {n:'POCO M7 Pro 5G',b:'Xiaomi',soc:'Dimensity 7025',ram:[8],os:'android'},
  {n:'POCO M6 Pro',b:'Xiaomi',soc:'Helio G99',ram:[8,12],os:'android'},
  {n:'POCO C75',b:'Xiaomi',soc:'Helio G81',ram:[6,8],os:'android'},
  {n:'Xiaomi Pad 7 Pro',b:'Xiaomi',soc:'Snapdragon 8s Gen 3',ram:[8,12],os:'android'},
  {n:'Xiaomi Pad 7',b:'Xiaomi',soc:'Snapdragon 7+ Gen 3',ram:[8,12],os:'android'},
  {n:'Xiaomi Pad 6',b:'Xiaomi',soc:'Snapdragon 870',ram:[6,8],os:'android'},
  {n:'Redmi Pad Pro',b:'Xiaomi',soc:'Snapdragon 7s Gen 2',ram:[6,8],os:'android'},
  {n:'Redmi Pad SE',b:'Xiaomi',soc:'Snapdragon 680',ram:[4,8],os:'android'},
  // ── 品牌：OPPO
  {n:'OPPO Find X9 / X9 Pro',b:'OPPO',soc:'Dimensity 9500',ram:[12,16],os:'android'},
  {n:'OPPO Find X8 / X8 Pro',b:'OPPO',soc:'Dimensity 9400',ram:[12,16],os:'android'},
  {n:'OPPO Find X8 Ultra',b:'OPPO',soc:'Snapdragon 8 Elite',ram:[12,16],os:'android'},
  {n:'OPPO Find N5',b:'OPPO',soc:'Snapdragon 8 Elite',ram:[16],os:'android'},
  {n:'OPPO Reno14 Pro',b:'OPPO',soc:'Dimensity 8450',ram:[12],os:'android'},
  {n:'OPPO Reno14',b:'OPPO',soc:'Dimensity 8350',ram:[12],os:'android'},
  {n:'OPPO Reno13 / Reno13 Pro',b:'OPPO',soc:'Dimensity 8350',ram:[12],os:'android'},
  {n:'OPPO Reno12 / Reno12 Pro',b:'OPPO',soc:'Dimensity 7300',ram:[12],os:'android'},
  {n:'OPPO Reno11 Pro',b:'OPPO',soc:'Dimensity 8200',ram:[12],os:'android'},
  {n:'OPPO Reno11',b:'OPPO',soc:'Dimensity 7050',ram:[12],os:'android'},
  {n:'OPPO Reno10 Pro+',b:'OPPO',soc:'Snapdragon 8+ Gen 1',ram:[12],os:'android'},
  {n:'OPPO Reno10 / Reno10 Pro',b:'OPPO',soc:'Snapdragon 778G',ram:[8,12],os:'android'},
  {n:'OPPO A5 Pro 5G',b:'OPPO',soc:'Dimensity 6300',ram:[8],os:'android'},
  {n:'OPPO A80 5G',b:'OPPO',soc:'Dimensity 6300',ram:[8],os:'android'},
  {n:'OPPO A3',b:'OPPO',soc:'Dimensity 6300',ram:[6,8],os:'android'},
  {n:'OPPO A79 5G',b:'OPPO',soc:'Dimensity 6020',ram:[8],os:'android'},
  {n:'OPPO A78 5G',b:'OPPO',soc:'Dimensity 700',ram:[8],os:'android'},
  {n:'OPPO A60',b:'OPPO',soc:'Snapdragon 680',ram:[8],os:'android'},
  // ── 品牌：vivo
  {n:'vivo X300 / X300 Pro',b:'vivo',soc:'Dimensity 9500',ram:[12,16],os:'android'},
  {n:'vivo X200 / X200 Pro',b:'vivo',soc:'Dimensity 9400',ram:[12,16],os:'android'},
  {n:'vivo X200 FE',b:'vivo',soc:'Dimensity 9300+',ram:[12],os:'android'},
  {n:'vivo X100 / X100 Pro',b:'vivo',soc:'Dimensity 9300',ram:[12,16],os:'android'},
  {n:'vivo V50',b:'vivo',soc:'Snapdragon 7 Gen 3',ram:[12],os:'android'},
  {n:'vivo V40',b:'vivo',soc:'Snapdragon 7 Gen 3',ram:[8,12],os:'android'},
  {n:'vivo V30',b:'vivo',soc:'Snapdragon 7 Gen 3',ram:[8,12],os:'android'},
  {n:'vivo V29',b:'vivo',soc:'Snapdragon 778G',ram:[8,12],os:'android'},
  {n:'vivo Y400 Pro',b:'vivo',soc:'Dimensity 7300',ram:[8],os:'android'},
  {n:'vivo Y300',b:'vivo',soc:'Snapdragon 4 Gen 2',ram:[8],os:'android'},
  {n:'vivo Y36',b:'vivo',soc:'Snapdragon 680',ram:[8],os:'android'},
  {n:'vivo Y28',b:'vivo',soc:'Helio G85',ram:[6,8],os:'android'},
  {n:'vivo Y19s',b:'vivo',soc:'Unisoc T612',ram:[4,6],os:'android'},
  // ── 品牌：realme
  {n:'realme GT 7 Pro',b:'realme',soc:'Snapdragon 8 Elite',ram:[12,16],os:'android'},
  {n:'realme GT 7',b:'realme',soc:'Dimensity 9400e',ram:[12],os:'android'},
  {n:'realme GT 7T',b:'realme',soc:'Dimensity 8400',ram:[12],os:'android'},
  {n:'realme GT 6',b:'realme',soc:'Snapdragon 8s Gen 3',ram:[12],os:'android'},
  {n:'realme GT 6T',b:'realme',soc:'Snapdragon 7+ Gen 3',ram:[8,12],os:'android'},
  {n:'realme 14 Pro+',b:'realme',soc:'Snapdragon 7s Gen 3',ram:[12],os:'android'},
  {n:'realme 13 Pro+',b:'realme',soc:'Snapdragon 7s Gen 2',ram:[12],os:'android'},
  {n:'realme 12 Pro+',b:'realme',soc:'Snapdragon 7s Gen 2',ram:[8,12],os:'android'},
  {n:'realme 14x',b:'realme',soc:'Dimensity 6300',ram:[6,8],os:'android'},
  {n:'realme C75',b:'realme',soc:'Helio G92 Max',ram:[8],os:'android'},
  {n:'realme C65',b:'realme',soc:'Helio G85',ram:[6,8],os:'android'},
  {n:'realme Note 60',b:'realme',soc:'Unisoc T612',ram:[4,6],os:'android'},
  // ── 品牌：ASUS
  {n:'ROG Phone 9 / 9 Pro',b:'ASUS',soc:'Snapdragon 8 Elite',ram:[12,16,24],os:'android'},
  {n:'ROG Phone 8 / 8 Pro',b:'ASUS',soc:'Snapdragon 8 Gen 3',ram:[12,16],os:'android'},
  {n:'ROG Phone 7 / 7 Ultimate',b:'ASUS',soc:'Snapdragon 8 Gen 2',ram:[12,16],os:'android'},
  {n:'ROG Phone 6 / 6 Pro',b:'ASUS',soc:'Snapdragon 8+ Gen 1',ram:[12,16],os:'android'},
  {n:'Zenfone 12 Ultra',b:'ASUS',soc:'Snapdragon 8 Elite',ram:[12,16],os:'android'},
  {n:'Zenfone 11 Ultra',b:'ASUS',soc:'Snapdragon 8 Gen 3',ram:[12,16],os:'android'},
  {n:'Zenfone 10',b:'ASUS',soc:'Snapdragon 8 Gen 2',ram:[8,16],os:'android'},
  {n:'Zenfone 9',b:'ASUS',soc:'Snapdragon 8+ Gen 1',ram:[8,16],os:'android'},
  {n:'Zenfone 8',b:'ASUS',soc:'Snapdragon 888',ram:[8,16],os:'android'},
  // ── 品牌：Sony
  {n:'Xperia 1 VII',b:'Sony',soc:'Snapdragon 8 Elite',ram:[12],os:'android'},
  {n:'Xperia 1 VI',b:'Sony',soc:'Snapdragon 8 Gen 3',ram:[12],os:'android'},
  {n:'Xperia 1 V',b:'Sony',soc:'Snapdragon 8 Gen 2',ram:[12],os:'android'},
  {n:'Xperia 5 V',b:'Sony',soc:'Snapdragon 8 Gen 2',ram:[8],os:'android'},
  {n:'Xperia 1 IV / 5 IV',b:'Sony',soc:'Snapdragon 8 Gen 1',ram:[8,12],os:'android'},
  {n:'Xperia 10 VI',b:'Sony',soc:'Snapdragon 6 Gen 1',ram:[8],os:'android'},
  {n:'Xperia 10 V',b:'Sony',soc:'Snapdragon 695',ram:[6,8],os:'android'},
  {n:'Xperia 10 IV',b:'Sony',soc:'Snapdragon 695',ram:[6],os:'android'},
  // ── 品牌：OnePlus
  {n:'OnePlus 13',b:'OnePlus',soc:'Snapdragon 8 Elite',ram:[12,16],os:'android'},
  {n:'OnePlus 13R',b:'OnePlus',soc:'Snapdragon 8 Gen 3',ram:[12],os:'android'},
  {n:'OnePlus 12',b:'OnePlus',soc:'Snapdragon 8 Gen 3',ram:[12,16],os:'android'},
  {n:'OnePlus 12R',b:'OnePlus',soc:'Snapdragon 8 Gen 2',ram:[8,16],os:'android'},
  {n:'OnePlus 11',b:'OnePlus',soc:'Snapdragon 8 Gen 2',ram:[8,16],os:'android'},
  {n:'OnePlus Nord 5',b:'OnePlus',soc:'Snapdragon 8s Gen 3',ram:[8,12],os:'android'},
  {n:'OnePlus Nord CE5',b:'OnePlus',soc:'Dimensity 8350',ram:[8],os:'android'},
  {n:'OnePlus Nord 4',b:'OnePlus',soc:'Snapdragon 7+ Gen 3',ram:[8,12],os:'android'},
  // ── 品牌：Nothing
  {n:'Nothing Phone (3)',b:'Nothing',soc:'Snapdragon 8s Gen 4',ram:[12,16],os:'android'},
  {n:'Nothing Phone (3a) / (3a) Pro',b:'Nothing',soc:'Snapdragon 7s Gen 3',ram:[8,12],os:'android'},
  {n:'Nothing Phone (2)',b:'Nothing',soc:'Snapdragon 8+ Gen 1',ram:[8,12],os:'android'},
  {n:'Nothing Phone (2a)',b:'Nothing',soc:'Dimensity 7200',ram:[8,12],os:'android'},
  {n:'CMF Phone 2 Pro',b:'Nothing',soc:'Dimensity 7300',ram:[8],os:'android'},
  {n:'CMF Phone 1',b:'Nothing',soc:'Dimensity 7300',ram:[6,8],os:'android'},
  // ── 品牌：HONOR／Huawei
  {n:'HONOR Magic7 Pro',b:'HONOR／Huawei',soc:'Snapdragon 8 Elite',ram:[12],os:'android'},
  {n:'HONOR Magic6 Pro',b:'HONOR／Huawei',soc:'Snapdragon 8 Gen 3',ram:[12],os:'android'},
  {n:'HONOR 400 / 400 Pro',b:'HONOR／Huawei',soc:'Snapdragon 7 Gen 3',ram:[8,12],os:'android'},
  {n:'HONOR 200',b:'HONOR／Huawei',soc:'Snapdragon 7 Gen 3',ram:[12],os:'android'},
  {n:'Huawei Pura 70',b:'HONOR／Huawei',soc:'Kirin 9010',ram:[12],os:'android'},
  {n:'Huawei Mate 60 Pro',b:'HONOR／Huawei',soc:'Kirin 9000s',ram:[12],os:'android'},
  {n:'Huawei P40 / P40 Pro',b:'HONOR／Huawei',soc:'Kirin 990',ram:[8],os:'android'},
  {n:'Huawei nova 7',b:'HONOR／Huawei',soc:'Kirin 985',ram:[8],os:'android'},
  // ── 品牌：其他
  {n:'motorola razr 60 ultra',b:'其他',soc:'Snapdragon 8 Elite',ram:[16],os:'android'},
  {n:'motorola edge 60 pro',b:'其他',soc:'Dimensity 8350',ram:[12],os:'android'},
  {n:'motorola edge 50 pro',b:'其他',soc:'Snapdragon 7 Gen 3',ram:[12],os:'android'},
  {n:'moto g85',b:'其他',soc:'Snapdragon 6s Gen 3',ram:[8],os:'android'},
  {n:'moto g55',b:'其他',soc:'Dimensity 7025',ram:[8],os:'android'},
  {n:'moto g35',b:'其他',soc:'Unisoc T760',ram:[4,8],os:'android'},
  {n:'HTC U24 pro',b:'其他',soc:'Snapdragon 7 Gen 3',ram:[12],os:'android'},
  {n:'Infinix GT 30 Pro',b:'其他',soc:'Dimensity 8350',ram:[12],os:'android'},
  {n:'Infinix Note 50 Pro+',b:'其他',soc:'Dimensity 8350',ram:[12],os:'android'},
  {n:'Tecno Pova 6 Pro',b:'其他',soc:'Dimensity 6080',ram:[8,12],os:'android'},
  {n:'Lenovo Legion Tab（Y700 2025）',b:'其他',soc:'Snapdragon 8 Gen 3',ram:[12,16],os:'android'},
  {n:'Lenovo Tab P12',b:'其他',soc:'Dimensity 7050',ram:[8],os:'android'},
];
