/* ============================================================
 * 遊戲需求資料庫  js/data-games.js
 * 每款遊戲：
 *   id 唯一代號  n 中文名  en 英文名  cat 分類（下拉選單的群組）
 *   verified true = 已對照官方頁面；false = 依公開資料整理
 *   upd 資料日期  src 來源網址  srcName 來源名稱  note 補充說明
 *   pc      {os:'win10'|'win7', min:{cpu:[…],gpu:[…],ram}, rec:{…}, high:{…}(選填), disk, ssd:'req'|'rec', note,
 *            via:PC 遊玩方式說明, viaKind:'official'|'emu'|'gpg'}   ← 手遊用
 *   android {min:{soc:[…],ram,os}, rec:{…}, disk, note}
 *   ios     {min:{chip,ram,os}, rec:{…}, disk, note}
 *   任一層加 est:true 代表該層為估算（畫面會標「估」）；沒有 rec 時引擎以最低 × 1.6 估算。
 *   硬體名稱必須與 data-hardware.js 完全一致；門檻取所列硬體中的最低分。
 * 新增遊戲：複製一筆改內容即可；用瀏覽器開啟 index.html 後，在網頁最下方也能手動新增／匯出 JSON。
 * ============================================================ */
const GAMES=[
  // ══════════ 二次元／開放世界 ══════════
  {id:'genshin',n:'原神',en:'Genshin Impact',cat:'二次元／開放世界',verified:true,upd:'2025-11（7.0）',src:'https://support.hoyoverse.com/hc/en-us/articles/52089402685593-What-are-the-system-requirements-to-play-Genshin-Impact',srcName:'HoYoverse 支援中心',
   pc:{os:'win10',min:{cpu:['Intel Core i5 第 6 代（泛指）'],gpu:['NVIDIA GeForce GTX 1050','Intel Iris Xe'],ram:8},rec:{cpu:['Intel Core i7 第 7 代（泛指）','AMD Ryzen 5000 系列（泛指）'],gpu:['NVIDIA GeForce GTX 1060 6GB'],ram:16},disk:110,ssd:'rec',note:'需 DirectX 11。官方建議安裝在 SSD。'},
   android:{min:{soc:['Snapdragon 660','Helio G88'],ram:4,os:10},rec:{soc:['Snapdragon 855','Dimensity 1000','Kirin 980'],ram:6,os:12},disk:40,diskRec:60,note:'7.0 起官方警告 Mali-G52 MP2、Mali-G57 MP、PowerVR、Imagination BXM 等 GPU（如 UNISOC T606～T619、Dimensity 7020／7025／7030／930、Helio P35／G36／G25）可能黑畫面或閃退。'},
   ios:{min:{chip:'Apple A11 Bionic',ram:3,os:14},rec:{chip:'Apple A13 Bionic',ram:4,os:14},disk:40,diskRec:60,note:'最低 iPhone 8 Plus／X，iPad 需 A12 以上；建議 iPhone 12 系列／iPad 9 以上。'}},
  {id:'hsr',n:'崩壞：星穹鐵道',en:'Honkai: Star Rail',cat:'二次元／開放世界',verified:true,upd:'2026-01（4.0）',src:'https://hsr.hoyoverse.com/',srcName:'HoYoverse 4.0 公告（2026-01 提高門檻）',
   pc:{os:'win10',min:{cpu:['Intel Core i5（泛指）'],gpu:['NVIDIA GeForce GTX 1050'],ram:8},rec:{cpu:['Intel Core i7（泛指）'],gpu:['NVIDIA GeForce GTX 1060 6GB'],ram:16},disk:82,ssd:'rec',note:'Windows 10／11 64 位元，DirectX 11。'},
   android:{min:{soc:['Snapdragon 835','Dimensity 720','Kirin 810'],ram:4,os:9},rec:{soc:['Snapdragon 870','Dimensity 1300','Kirin 9000'],ram:6},disk:40},
   ios:{min:{chip:'Apple A11 Bionic',ram:3,os:13},rec:{chip:'Apple A13 Bionic',ram:4},disk:42,note:'最低 iPhone 8 Plus／iPad A10 以上；建議 iPhone 11／iPad A13／iPad mini A15／iPad Pro M1 以上。'}},
  {id:'zzz',n:'絕區零',en:'Zenless Zone Zero',cat:'二次元／開放世界',verified:true,upd:'2025',src:'https://support.hoyoverse.com/hc/en-us/articles/49686220608793-Minimum-device-requirements-for-Zenless-Zone-Zero',srcName:'HoYoverse 支援中心',
   pc:{os:'win10',min:{cpu:['Intel Core i5 第 7 代（泛指）'],gpu:['NVIDIA GeForce GTX 970'],ram:8},rec:{cpu:['Intel Core i7 第 10 代（泛指）'],gpu:['NVIDIA GeForce GTX 1660'],ram:8},disk:115,ssd:'rec',note:'DirectX 11.1。安裝約 57GB，解壓另需約 58GB 暫存空間。'},
   android:{min:{soc:['Snapdragon 855','Dimensity 1200','Kirin 990'],ram:8,os:11},rec:{soc:['Snapdragon 8 Gen 1','Dimensity 9000'],ram:8,est:true},disk:20},
   ios:{min:{chip:'Apple A12 Bionic',ram:4,os:14},rec:{chip:'Apple A13 Bionic',ram:4},disk:26,note:'最低 iPhone XS／iPad A12 以上；建議 iPhone 11 Pro 以上。'}},
  {id:'wuwa',n:'鳴潮',en:'Wuthering Waves',cat:'二次元／開放世界',verified:true,upd:'2025-09（2.3+）',src:'https://wutheringwaves.kurogames.com/',srcName:'庫洛官方公告（17173 整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5 第 9 代（泛指）','AMD Ryzen 7 2700'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 570'],ram:16},rec:{cpu:['Intel Core i7 第 9 代（泛指）','AMD Ryzen 7 3700X'],gpu:['NVIDIA GeForce RTX 2060','AMD Radeon RX 5700 XT','Intel Arc A750'],ram:16},disk:70,ssd:'rec'},
   android:{min:{soc:['Snapdragon 835','Kirin 970'],ram:4,os:7},rec:{soc:['Snapdragon 8+ Gen 1','Snapdragon 8 Gen 2','Snapdragon 8 Gen 3'],ram:6},disk:31,note:'最低約 Snapdragon 835／Mali-G71～G72 等級。'},
   ios:{min:{chip:'Apple A13 Bionic',ram:4,os:14},rec:{chip:'Apple A15 Bionic',ram:6,os:15},disk:31,note:'最低 iPhone 11；建議 iPhone 13 以上。'}},
  {id:'endfield',n:'明日方舟：終末地',en:'Arknights: Endfield',cat:'二次元／開放世界',verified:true,upd:'2026-01',src:'https://endfield.gryphline.com/',srcName:'鷹角網路官方公告',
   pc:{os:'win10',min:{cpu:['Intel Core i5-9400F'],gpu:['NVIDIA GeForce GTX 1060 6GB'],ram:16},rec:{cpu:['Intel Core i7-10700K'],gpu:['NVIDIA GeForce RTX 2060'],ram:16},disk:100,ssd:'rec',note:'DirectX 11.1。本體約 55GB，解壓縮時另需 45GB 暫存，請預留 100GB。'},
   android:{min:{soc:['Snapdragon 855','Dimensity 1000','Kirin 990'],ram:6,os:10},rec:{soc:['Snapdragon 8+ Gen 1','Dimensity 9000','Kirin 9000s'],ram:8,os:11},disk:28},
   ios:{min:{chip:'Apple A13 Bionic',ram:4,os:15},rec:{chip:'Apple A15 Bionic',ram:6},disk:28,note:'最低 iPhone 11／A13 iPad；建議 iPhone 13 Pro 以上。'}},
  {id:'wwm',n:'燕雲十六聲',en:'Where Winds Meet',cat:'二次元／開放世界',verified:false,upd:'2025-12',src:'https://www.wherewindsmeet.com/',srcName:'NetEase 官方（手機需求已對照官方公告；PC 依 Steam 頁整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:16},rec:{cpu:['Intel Core i7-10700','AMD Ryzen 7 5800X'],gpu:['NVIDIA GeForce RTX 3060','AMD Radeon RX 6700 XT'],ram:32},disk:100,ssd:'req',note:'另有需求較低的 Lite 客戶端（GTX 750 Ti／RX 550 2GB 即可啟動）。更新時暫存可能用到 200GB。'},
   android:{min:{soc:['Snapdragon 778G','Dimensity 1000L','Exynos 2100'],ram:8,os:7.1},rec:{soc:['Snapdragon 8 Gen 2','Dimensity 9200','Exynos 2400'],ram:8},disk:30,note:'官方另列「支援」層級：Snapdragon 7+ Gen 2／Dimensity 8000／Exynos 2200。'},
   ios:{min:{chip:'Apple A13 Bionic',ram:4,os:15},rec:{chip:'Apple A16 Bionic',ram:6},disk:30,note:'最低 iPhone 11；支援 iPhone 12 Pro；建議 iPhone 14 Pro 以上。'}},
  {id:'nikke',n:'勝利女神：妮姬',en:'GODDESS OF VICTORY: NIKKE',cat:'二次元／開放世界',verified:true,upd:'2023-02（PC 需求）',src:'https://nikke-en.com/',srcName:'Shift Up 官方（PC 需求）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win7',min:{cpu:['Intel Core i3（泛指）'],gpu:['NVIDIA GeForce GTX 750 Ti'],ram:8},rec:{cpu:['Intel Core i5（泛指）'],gpu:['NVIDIA GeForce GTX 1650 SUPER','NVIDIA GeForce GTX 1650'],ram:8},disk:20,note:'官方 PC 版，帳號與手機雲端同步。'},
   android:{min:{soc:['Snapdragon 660'],ram:4,os:7,est:true},rec:{soc:['Snapdragon 855'],ram:6,est:true},disk:15},
   ios:{min:{chip:'Apple A11 Bionic',ram:3,os:13,est:true},rec:{chip:'Apple A13 Bionic',ram:4,est:true},disk:15}},
  {id:'nikki',n:'無限暖暖',en:'Infinity Nikki',cat:'二次元／開放世界',verified:false,upd:'2025',src:'https://infinitynikki.infoldgames.com/',srcName:'疊紙官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i7-7700','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:16},rec:{cpu:['Intel Core i7-9700','AMD Ryzen 7 3700X'],gpu:['NVIDIA GeForce RTX 3060','AMD Radeon RX 6700 XT'],ram:16,est:true},disk:80,ssd:'rec'},
   android:{min:{soc:['Snapdragon 855','Dimensity 1000','Kirin 990'],ram:6,os:9,est:true},rec:{soc:['Snapdragon 8 Gen 2','Dimensity 9200'],ram:8,est:true},disk:20},
   ios:{min:{chip:'Apple A13 Bionic',ram:4,os:14,est:true},rec:{chip:'Apple A16 Bionic',ram:6,est:true},disk:20}},
  {id:'hi3',n:'崩壞3rd',en:'Honkai Impact 3rd',cat:'二次元／開放世界',verified:false,upd:'2025',src:'https://honkaiimpact3.hoyoverse.com/',srcName:'HoYoverse 官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i3-6100'],gpu:['NVIDIA GeForce GTX 750 Ti'],ram:8,est:true},rec:{cpu:['Intel Core i5-8400'],gpu:['NVIDIA GeForce GTX 1060 6GB'],ram:16,est:true},disk:30,ssd:'rec'},
   android:{min:{soc:['Snapdragon 730G','Dimensity 800'],ram:4,os:8,est:true},rec:{soc:['Snapdragon 8 Gen 1','Dimensity 9000'],ram:8,est:true},disk:20},
   ios:{min:{chip:'Apple A12 Bionic',ram:3,os:14,est:true},rec:{chip:'Apple A15 Bionic',ram:6,est:true},disk:20}},
  {id:'tof',n:'幻塔',en:'Tower of Fantasy',cat:'二次元／開放世界',verified:false,upd:'2025',src:'https://tof.perfectworld.com/',srcName:'完美世界官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i5（泛指）'],gpu:['NVIDIA GeForce GTX 1050'],ram:8,est:true},rec:{cpu:['Intel Core i7-8700'],gpu:['NVIDIA GeForce GTX 1660'],ram:16,est:true},disk:40,ssd:'rec'},
   android:{min:{soc:['Snapdragon 845'],ram:4,os:7,est:true},rec:{soc:['Snapdragon 888'],ram:8,est:true},disk:20},
   ios:{min:{chip:'Apple A12 Bionic',ram:3,os:12,est:true},rec:{chip:'Apple A14 Bionic',ram:4,est:true},disk:20}},
  {id:'gfl2',n:'少女前線2：追放',en:"Girls' Frontline 2: Exilium",cat:'二次元／開放世界',verified:false,upd:'2025',src:'https://gf2exilium.sunborngame.com/',srcName:'散爆官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i5-6500'],gpu:['NVIDIA GeForce GTX 1050 Ti'],ram:8,est:true},rec:{cpu:['Intel Core i5-10400'],gpu:['NVIDIA GeForce GTX 1660 SUPER'],ram:16,est:true},disk:30,ssd:'rec'},
   android:{min:{soc:['Snapdragon 845'],ram:4,os:8,est:true},rec:{soc:['Snapdragon 8 Gen 1'],ram:8,est:true},disk:15},
   ios:{min:{chip:'Apple A12 Bionic',ram:3,os:13,est:true},rec:{chip:'Apple A15 Bionic',ram:6,est:true},disk:15}},
  {id:'snowbreak',n:'塵白禁區',en:'Snowbreak: Containment Zone',cat:'二次元／開放世界',verified:false,upd:'2025',src:'https://snowbreak.amazingseasun.com/',srcName:'西山居官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i5-6500'],gpu:['NVIDIA GeForce GTX 1050'],ram:8,est:true},rec:{cpu:['Intel Core i7-8700'],gpu:['NVIDIA GeForce GTX 1660'],ram:16,est:true},disk:30,ssd:'rec'},
   android:{min:{soc:['Snapdragon 845'],ram:4,os:8,est:true},rec:{soc:['Snapdragon 8 Gen 1'],ram:8,est:true},disk:15},
   ios:{min:{chip:'Apple A12 Bionic',ram:3,os:13,est:true},rec:{chip:'Apple A15 Bionic',ram:6,est:true},disk:15}},
  {id:'sky',n:'光‧遇',en:'Sky: Children of the Light',cat:'二次元／開放世界',verified:false,upd:'2025',src:'https://www.thatskygame.com/',srcName:'thatgamecompany 官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i5-3470'],gpu:['NVIDIA GeForce GTX 660'],ram:4,est:true},rec:{cpu:['Intel Core i5-8400'],gpu:['NVIDIA GeForce GTX 1050 Ti'],ram:8,est:true},disk:6,note:'Steam 官方 PC 版。'},
   android:{min:{soc:['Snapdragon 636'],ram:3,os:7,est:true},rec:{soc:['Snapdragon 855'],ram:4,est:true},disk:5},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:13,est:true},rec:{chip:'Apple A13 Bionic',ram:4,est:true},disk:5}},
  {id:'lds',n:'戀與深空',en:'Love and Deepspace',cat:'二次元／開放世界',verified:false,upd:'2025',src:'https://loveanddeepspace.infoldgames.com/',srcName:'疊紙官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-4150','AMD FX-6300'],gpu:['Intel HD Graphics 4000','NVIDIA GeForce GT 730'],ram:4},rec:{cpu:['Intel Core i5-6500','AMD Ryzen 5 1400'],gpu:['NVIDIA GeForce GTX 1050','AMD Radeon RX 560'],ram:8,est:true},disk:10,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、Intel／AMD 處理器、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。建議欄為 3D 手遊順跑的估算值。'},
   android:{min:{soc:['Snapdragon 845'],ram:6,os:8,est:true},rec:{soc:['Snapdragon 8 Gen 1'],ram:8,est:true},disk:15},
   ios:{min:{chip:'Apple A12 Bionic',ram:4,os:14,est:true},rec:{chip:'Apple A15 Bionic',ram:6,est:true},disk:15}},

  // ══════════ 射擊／戰術競技 ══════════
  {id:'delta',n:'三角洲行動',en:'Delta Force',cat:'射擊／戰術競技',verified:true,upd:'2025',src:'https://store.steampowered.com/app/2507950/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i3-4150','AMD FX-6300'],gpu:['NVIDIA GeForce GTX 660','AMD Radeon HD 7870','Intel Arc A380'],ram:8},rec:{cpu:['Intel Core i5-6500','AMD Ryzen 5 1500X'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 5500 XT','Intel Arc A580'],ram:16},disk:88,ssd:'rec',note:'DirectX 12。'},
   android:{min:{soc:['Snapdragon 450'],ram:4,os:7},rec:{soc:['Snapdragon 865','Snapdragon 7s Gen 3'],ram:8,os:10},disk:7,diskRec:15,note:'最低 Android 7.1。'},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:12},rec:{chip:'Apple A13 Bionic',ram:4},disk:10,diskRec:15,note:'最低 iPhone 7；建議 iPhone 12（A13 以上）。'}},
  {id:'valorant',n:'特戰英豪',en:'VALORANT',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://playvalorant.com/',srcName:'Riot Games 官方',
   pc:{os:'win10',min:{cpu:['Intel Core 2 Duo E8400','AMD Athlon 200GE'],gpu:['Intel HD Graphics 4000','AMD Radeon R5 200'],ram:4},rec:{cpu:['Intel Core i3-4150','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GT 730','AMD Radeon R7 240'],ram:4},high:{cpu:['Intel Core i5-9400F','AMD Ryzen 5 2600X'],gpu:['NVIDIA GeForce GTX 1050 Ti','AMD Radeon R7 370'],ram:4,label:'高規（144+ fps）'},disk:40,note:'最低＝30fps、建議＝60fps、高規＝144fps 以上。Windows 11 必須開啟 TPM 2.0 與安全開機（Vanguard 反作弊）。'}},
  {id:'apex',n:'Apex 英雄',en:'Apex Legends',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1172470/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i3-6300','AMD FX-4350'],gpu:['NVIDIA GeForce GT 640','AMD Radeon HD 7730'],ram:6},rec:{cpu:['Intel Core i5-3570K','AMD Ryzen 5（泛指）'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon R9 290'],ram:8},disk:75,note:'DirectX 11；建議顯示記憶體 8GB。'}},
  {id:'fortnite',n:'要塞英雄',en:'Fortnite',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://www.fortnite.com/',srcName:'Epic Games 官方',
   pc:{os:'win10',min:{cpu:['Intel Core i3-3225'],gpu:['Intel HD Graphics 4000','AMD Radeon Vega 8'],ram:8},rec:{cpu:['Intel Core i5-7300U'],gpu:['NVIDIA GeForce GTX 960','AMD Radeon R9 280'],ram:16},high:{cpu:['Intel Core i7-8700','AMD Ryzen 7 3700X'],gpu:['NVIDIA GeForce RTX 3070','AMD Radeon RX 6700 XT'],ram:16,label:'Epic 畫質'},disk:40,ssd:'rec',note:'Epic 畫質層需 8GB 顯示記憶體與 NVMe SSD。'},
   android:{min:{soc:['Snapdragon 820','Kirin 970'],ram:4,os:8},rec:{soc:['Snapdragon 855'],ram:6,est:true},disk:6,note:'需透過 Epic Games Store／Samsung Galaxy Store 安裝；最低 Adreno 530／Mali-G72 MP12 等級。iOS 版在台灣無法自 App Store 安裝。'}},
  {id:'cs2',n:'Counter-Strike 2',en:'Counter-Strike 2',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://store.steampowered.com/app/730/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-750'],gpu:['DirectX 11 相容 1GB 顯示卡（泛指）'],ram:8},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:16,est:true},disk:85,note:'官方僅列最低配備（4 執行緒 CPU、DirectX 11／Shader Model 5.0）；建議配備為估算。'}},
  {id:'pubg',n:'PUBG: BATTLEGROUNDS',en:'PUBG: Battlegrounds',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://store.steampowered.com/app/578080/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-4430','AMD FX-6300'],gpu:['NVIDIA GeForce GTX 960','AMD Radeon R7 370'],ram:8},rec:{cpu:['Intel Core i5-6600K','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1060 3GB','AMD Radeon RX 580'],ram:16},disk:40,diskRec:50,note:'DirectX 11。'}},
  {id:'ow2',n:'鬥陣特攻 2',en:'Overwatch 2',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://overwatch.blizzard.com/',srcName:'Blizzard 官方',
   pc:{os:'win10',min:{cpu:['Intel Core i3（泛指）','AMD Phenom X3 8650'],gpu:['NVIDIA GeForce GTX 600 系列（泛指）','AMD Radeon HD 7000 系列（泛指）'],ram:6},rec:{cpu:['Intel Core i7（泛指）','AMD Ryzen 5（泛指）'],gpu:['NVIDIA GeForce GTX 1060 6GB','NVIDIA GeForce GTX 1650','AMD Radeon RX 6400'],ram:8},disk:50}},
  {id:'rivals',n:'漫威爭鋒',en:'Marvel Rivals',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2767030/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-6600K','AMD Ryzen 5 1600X'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580','Intel Arc A380'],ram:16},rec:{cpu:['Intel Core i5-10400','AMD Ryzen 5 5600X'],gpu:['NVIDIA GeForce RTX 2060 SUPER','AMD Radeon RX 5700 XT','Intel Arc A750'],ram:16},disk:70,ssd:'req',note:'DirectX 12，官方要求 SSD。'}},
  {id:'bf6',n:'戰地風雲 6',en:'Battlefield 6',cat:'射擊／戰術競技',verified:false,upd:'2025-10',src:'https://www.ea.com/games/battlefield/battlefield-6',srcName:'EA 官方',
   pc:{os:'win10',min:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce RTX 2060','AMD Radeon RX 5600 XT','Intel Arc A380'],ram:16},rec:{cpu:['Intel Core i7-10700','AMD Ryzen 7 3700X'],gpu:['NVIDIA GeForce RTX 3060 Ti','AMD Radeon RX 6700 XT','Intel Arc B580'],ram:16},high:{cpu:['Intel Core i9-12900K','AMD Ryzen 7 7800X3D'],gpu:['NVIDIA GeForce RTX 4080','AMD Radeon RX 7900 XTX'],ram:32,label:'Ultra（4K／60）'},disk:55,diskRec:80,ssd:'rec',note:'必須開啟 TPM 2.0、安全開機與 HVCI／VBS（Javelin 反作弊）。'}},
  {id:'r6x',n:'虹彩六號：圍攻行動 X',en:'Rainbow Six Siege X',cat:'射擊／戰術競技',verified:false,upd:'2025-06',src:'https://www.ubisoft.com/game/rainbow-six/siege',srcName:'Ubisoft 官方',
   pc:{os:'win10',min:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 960','AMD Radeon RX 560'],ram:8},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1660','AMD Radeon RX 5600 XT'],ram:16},disk:100,ssd:'rec',note:'DirectX 11。'}},
  {id:'cod',n:'決勝時刻：黑色行動 6／7・Warzone',en:'Call of Duty: Black Ops 6 / 7 · Warzone',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://www.callofduty.com/',srcName:'Activision 官方',
   pc:{os:'win10',min:{cpu:['Intel Core i5-6600','AMD Ryzen 5 1400'],gpu:['NVIDIA GeForce GTX 960','AMD Radeon RX 470','Intel Arc A580'],ram:8},rec:{cpu:['Intel Core i7-6700K','AMD Ryzen 5 1600X'],gpu:['NVIDIA GeForce RTX 3060','AMD Radeon RX 6600 XT','Intel Arc A770'],ram:12},disk:102,ssd:'req',note:'DirectX 12，官方要求 SSD；完整安裝含 Warzone 空間更大。'}},
  {id:'helldivers2',n:'絕地戰兵 2',en:'Helldivers 2',cat:'射擊／戰術競技',verified:false,upd:'2024',src:'https://store.steampowered.com/app/553850/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i7-4790K','AMD Ryzen 7 1700'],gpu:['NVIDIA GeForce GTX 1050 Ti','AMD Radeon RX 470'],ram:8},rec:{cpu:['Intel Core i7-9700K','AMD Ryzen 7 3700X'],gpu:['NVIDIA GeForce RTX 2060','AMD Radeon RX 6600 XT'],ram:16},disk:100,ssd:'rec'}},
  {id:'thefinals',n:'THE FINALS',en:'THE FINALS',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2073850/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-6600K','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1050 Ti','AMD Radeon RX 580'],ram:12},rec:{cpu:['Intel Core i5-9600K','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce RTX 2070','AMD Radeon RX 5700 XT'],ram:16},disk:30,ssd:'rec'}},
  {id:'arcraiders',n:'ARC Raiders',en:'ARC Raiders',cat:'射擊／戰術競技',verified:true,upd:'2025-10',src:'https://store.steampowered.com/app/1808500/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-6600K','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1050 Ti','AMD Radeon RX 580','Intel Arc A380'],ram:12},rec:{cpu:['Intel Core i5-9600K','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce RTX 2070'],ram:16},disk:35,ssd:'rec',note:'DirectX 12。官方未列儲存空間，實裝約 33GB。'}},
  {id:'abi',n:'暗區突圍：無限',en:'Arena Breakout: Infinite',cat:'射擊／戰術競技',verified:true,upd:'2025-08',src:'https://store.steampowered.com/app/3001120/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GTX 960','AMD Radeon RX 570','Intel Arc A380'],ram:16},rec:{cpu:['Intel Core i7-9700','AMD Ryzen 5 3600X'],gpu:['NVIDIA GeForce RTX 2060','AMD Radeon RX 6600'],ram:16},disk:70,ssd:'rec',note:'DirectX 12。'}},
  {id:'warframe',n:'Warframe',en:'Warframe',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://www.warframe.com/',srcName:'Digital Extremes 官方',
   pc:{os:'win10',min:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 760','AMD Radeon RX 560'],ram:8},rec:{cpu:['Intel Core i7-8700K','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce GTX 1660','AMD Radeon RX 5600 XT'],ram:16,est:true},disk:50,ssd:'rec'}},
  {id:'destiny2',n:'天命 2',en:'Destiny 2',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1085660/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i3-3240','AMD FX-4350'],gpu:['NVIDIA GeForce GTX 660','AMD Radeon HD 7850'],ram:6},rec:{cpu:['Intel Core i5-2400','AMD Ryzen 5 1600X'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon R9 390'],ram:8},disk:105,ssd:'rec'}},
  {id:'rust',n:'Rust',en:'Rust',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://store.steampowered.com/app/252490/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i7-3770','AMD FX-9590'],gpu:['NVIDIA GeForce GTX 670','AMD Radeon R9 280'],ram:10},rec:{cpu:['Intel Core i7-4790K','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 980','AMD Radeon R9 Fury'],ram:16},disk:25,ssd:'req'}},
  {id:'tarkov',n:'逃離塔科夫',en:'Escape from Tarkov',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://www.escapefromtarkov.com/',srcName:'Battlestate 官方（非 Steam）',
   pc:{os:'win10',min:{cpu:['Intel Core i3（泛指）'],gpu:['DirectX 11 相容 1GB 顯示卡（泛指）'],ram:8},rec:{cpu:['Intel Core i5（泛指）'],gpu:['NVIDIA GeForce GTX 1060 3GB'],ram:16,est:true},disk:40,ssd:'rec',note:'官方只寫雙核心 2.4GHz／四核心 3.2GHz 與顯示記憶體 1GB／2GB，此處以同等硬體換算。'}},
  {id:'naraka',n:'永劫無間',en:'NARAKA: BLADEPOINT',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1203220/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-4590','AMD FX-8350'],gpu:['NVIDIA GeForce GTX 750 Ti','AMD Radeon R7 260X'],ram:8,est:true},rec:{cpu:['Intel Core i7-7700K','AMD Ryzen 7 1700'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:16},disk:35,ssd:'rec'},
   android:{min:{soc:['Snapdragon 845'],ram:4,os:8,est:true},rec:{soc:['Snapdragon 888'],ram:8,est:true},disk:10},
   ios:{min:{chip:'Apple A12 Bionic',ram:3,os:13,est:true},rec:{chip:'Apple A15 Bionic',ram:6,est:true},disk:10}},
  {id:'oncehuman',n:'七日世界',en:'Once Human',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://www.oncehuman.game/',srcName:'NetEase 官方（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-4460','AMD Ryzen 5 1400'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon RX 570'],ram:8,est:true},rec:{cpu:['Intel Core i7-8700','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce RTX 2060','AMD Radeon RX 5700'],ram:16,est:true},disk:100,ssd:'rec'},
   android:{min:{soc:['Snapdragon 855'],ram:6,os:9,est:true},rec:{soc:['Snapdragon 8 Gen 2'],ram:8,est:true},disk:15},
   ios:{min:{chip:'Apple A13 Bionic',ram:4,os:14,est:true},rec:{chip:'Apple A16 Bionic',ram:6,est:true},disk:15}},
  {id:'tf2',n:'絕地要塞 2',en:'Team Fortress 2',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://store.steampowered.com/app/440/',srcName:'Steam 商店頁',
   pc:{os:'win7',min:{cpu:['1.6GHz 處理器（泛指）'],gpu:['DirectX 10 相容顯示卡（泛指）'],ram:1},rec:{cpu:['雙核心 2.8GHz 處理器（泛指）'],gpu:['NVIDIA GeForce 8600 GT'],ram:2,est:true},disk:15}},
  {id:'l4d2',n:'惡靈勢力 2',en:'Left 4 Dead 2',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://store.steampowered.com/app/550/',srcName:'Steam 商店頁',
   pc:{os:'win7',min:{cpu:['1.6GHz 處理器（泛指）'],gpu:['DirectX 10 相容顯示卡（泛指）'],ram:2},rec:{cpu:['雙核心 2.8GHz 處理器（泛指）'],gpu:['NVIDIA GeForce 8600 GT'],ram:2,est:true},disk:13}},
  {id:'warthunder',n:'War Thunder',en:'War Thunder',cat:'射擊／戰術競技',verified:false,upd:'2025',src:'https://warthunder.com/',srcName:'Gaijin 官方（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['雙核心 2.8GHz 處理器（泛指）'],gpu:['Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i5-4570','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 570'],ram:16,est:true},disk:100,ssd:'rec'}},

  // ══════════ MOBA／競技 ══════════
  {id:'lol',n:'英雄聯盟',en:'League of Legends',cat:'MOBA／競技',verified:false,upd:'2025',src:'https://support-leagueoflegends.riotgames.com/',srcName:'Riot Games 支援中心',
   pc:{os:'win10',min:{cpu:['Intel Core i3-530','AMD A6-3650'],gpu:['NVIDIA GeForce 9600 GT','AMD Radeon HD 6570','Intel HD Graphics 4600'],ram:2},rec:{cpu:['Intel Core i5-3300','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 560','AMD Radeon HD 6950','Intel UHD Graphics 630'],ram:4},disk:16,ssd:'rec',note:'最低 DirectX 10；建議 DirectX 11、SSD。Windows 11 需開啟 TPM 2.0（Vanguard）。'}},
  {id:'dota2',n:'Dota 2',en:'Dota 2',cat:'MOBA／競技',verified:false,upd:'2025',src:'https://store.steampowered.com/app/570/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['雙核心 2.8GHz 處理器（泛指）'],gpu:['NVIDIA GeForce 8600 GT','NVIDIA GeForce 9600 GT'],ram:4},rec:{cpu:['Intel Core i5-4460'],gpu:['NVIDIA GeForce GTX 750 Ti'],ram:8,est:true},disk:60,note:'官方僅列最低配備（DirectX 11）；建議配備為估算。'}},
  {id:'aov',n:'Garena 傳說對決',en:'Arena of Valor',cat:'MOBA／競技',verified:true,upd:'官方公告',src:'https://moba.garena.tw/news/show/3996',srcName:'Garena 官方',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-4150','AMD FX-6300'],gpu:['Intel HD Graphics 4000','NVIDIA GeForce GT 730'],ram:4},rec:{cpu:['Intel Core i5-6500','AMD Ryzen 5 1400'],gpu:['NVIDIA GeForce GTX 1050','AMD Radeon RX 560'],ram:8,est:true},disk:10,ssd:'rec',note:'官方沒有電腦版；PC 可用 GameLoop、BlueStacks、LDPlayer、夜神等模擬器遊玩，以上為模擬器需求（需開啟虛擬化 VT）。建議欄為估算。'},
   android:{min:{soc:['四核心 1.2GHz 處理器（泛指）'],ram:1,os:4},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:3,note:'官方最低：Android 4.4、四核心 1.2GHz、1GB RAM。'},
   ios:{min:{chip:'Apple A8',ram:1,os:10},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:3,note:'官方最低：iOS 10、iPhone 6。'}},
  {id:'wildrift',n:'英雄聯盟：激鬥峽谷',en:'League of Legends: Wild Rift',cat:'MOBA／競技',verified:false,upd:'2025',src:'https://wildrift.leagueoflegends.com/',srcName:'Riot Games 官方',note:'Riot 不支援模擬器，沒有 PC 版。',
   android:{min:{soc:['Snapdragon 430'],ram:2,os:5},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:4,note:'官方最低約 1.5GHz 八核心、Adreno 306 等級（以 Snapdragon 430 近似）。'},
   ios:{min:{chip:'Apple A8',ram:1,os:12},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:4}},
  {id:'mlbb',n:'Mobile Legends: Bang Bang',en:'Mobile Legends: Bang Bang',cat:'MOBA／競技',verified:false,upd:'2025',src:'https://m.mobilelegends.com/',srcName:'Moonton 官方',
   pc:{via:'Google Play Games（PC 版，Google 官方）',viaKind:'gpg',os:'win10',min:{cpu:['Intel Core i5-6400','AMD Ryzen 3 1200'],gpu:['Intel UHD Graphics 630'],ram:8},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:10,ssd:'req',note:'PC 是透過 Google 官方的 Google Play Games（PC）遊玩。官方最低：Windows 10（2004）以上、4 個實體核心、Intel UHD 630 等級以上、8GB RAM、SSD 10GB、需開啟硬體虛擬化。建議欄為估算。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:5,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:3},
   ios:{min:{chip:'Apple A9',ram:2,os:12,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:3}},
  {id:'tft',n:'聯盟戰棋',en:'Teamfight Tactics',cat:'MOBA／競技',verified:false,upd:'2025',src:'https://teamfighttactics.leagueoflegends.com/',srcName:'Riot 官方（PC 與英雄聯盟相同）',
   pc:{os:'win10',min:{cpu:['Intel Core i3-530','AMD A6-3650'],gpu:['NVIDIA GeForce 9600 GT','AMD Radeon HD 6570','Intel HD Graphics 4600'],ram:2},rec:{cpu:['Intel Core i5-3300','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 560','AMD Radeon HD 6950','Intel UHD Graphics 630'],ram:4},disk:16,ssd:'rec'},
   android:{min:{soc:['Snapdragon 625'],ram:3,os:7,est:true},rec:{soc:['Snapdragon 730G'],ram:4,est:true},disk:4},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:13,est:true},rec:{chip:'Apple A12 Bionic',ram:4,est:true},disk:4}},
  {id:'hok',n:'王者榮耀（國際版）',en:'Honor of Kings',cat:'MOBA／競技',verified:false,upd:'2025',src:'https://www.honorofkings.com/',srcName:'Level Infinite 官方（依公開資料整理）',
   pc:{via:'GameLoop 模擬器（騰訊官方）',viaKind:'emu',os:'win7',min:{cpu:['雙核心 2.8GHz 處理器（泛指）'],gpu:['NVIDIA GeForce 8600 GT','Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i3-530','AMD Phenom II X4 955'],gpu:['NVIDIA GeForce GTX 460','AMD Radeon HD 5870'],ram:8,est:true},disk:10,ssd:'rec',note:'PC 是透過 GameLoop（騰訊官方 Android 模擬器）遊玩，以上為模擬器需求；需在 BIOS 開啟虛擬化（VT-x／AMD-V）。實際 3D 手遊要順跑，建議至少 GTX 1050 等級顯示卡。'},
   android:{min:{soc:['Snapdragon 450'],ram:3,os:6,est:true},rec:{soc:['Snapdragon 855'],ram:6,est:true},disk:8},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:13,est:true},rec:{chip:'Apple A13 Bionic',ram:4,est:true},disk:8}},
  {id:'pokemonunite',n:'Pokémon UNITE',en:'Pokémon UNITE',cat:'MOBA／競技',verified:false,upd:'2025',src:'https://unite.pokemon.com/',srcName:'官方（依公開資料整理）',
   android:{min:{soc:['Snapdragon 636'],ram:3,os:6,est:true},rec:{soc:['Snapdragon 845'],ram:4,est:true},disk:4},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:13,est:true},rec:{chip:'Apple A12 Bionic',ram:4,est:true},disk:4}},

  // ══════════ 單機大作／動作 RPG ══════════
  {id:'wukong',n:'黑神話：悟空',en:'Black Myth: Wukong',cat:'單機大作／動作 RPG',verified:false,upd:'2024-08',src:'https://store.steampowered.com/app/2358720/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-8400','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:16},rec:{cpu:['Intel Core i7-9700','AMD Ryzen 5 5500'],gpu:['NVIDIA GeForce RTX 2060','AMD Radeon RX 5700 XT','Intel Arc A750'],ram:16},disk:130,ssd:'rec',note:'DirectX 11；最低＝1080p 低畫質 30fps、建議＝1080p 中畫質 60fps。'}},
  {id:'eldenring',n:'艾爾登法環',en:'ELDEN RING',cat:'單機大作／動作 RPG',verified:false,upd:'2024',src:'https://store.steampowered.com/app/1245620/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-8400','AMD Ryzen 3 3300X'],gpu:['NVIDIA GeForce GTX 1060 3GB','AMD Radeon RX 580'],ram:12},rec:{cpu:['Intel Core i7-8700K','AMD Ryzen 5 3600X'],gpu:['NVIDIA GeForce GTX 1070','AMD Radeon RX Vega 56'],ram:16},disk:60,note:'DirectX 12。'}},
  {id:'nightreign',n:'艾爾登法環：黑夜君臨',en:'ELDEN RING NIGHTREIGN',cat:'單機大作／動作 RPG',verified:false,upd:'2025-05',src:'https://store.steampowered.com/app/2622380/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-8400','AMD Ryzen 3 3300X'],gpu:['NVIDIA GeForce GTX 1060 3GB','AMD Radeon RX 580'],ram:12},rec:{cpu:['Intel Core i7-8700K','AMD Ryzen 5 3600X'],gpu:['NVIDIA GeForce GTX 1070','AMD Radeon RX Vega 56'],ram:16},disk:30,note:'DirectX 12，需求與本傳相同。'}},
  {id:'cp2077',n:'電馭叛客 2077（2.0／自由幻局）',en:'Cyberpunk 2077',cat:'單機大作／動作 RPG',verified:false,upd:'2023-09（2.0）',src:'https://www.cyberpunk.net/',srcName:'CD PROJEKT RED 官方',
   pc:{os:'win10',min:{cpu:['Intel Core i7-6700','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580','Intel Arc A380'],ram:12},rec:{cpu:['Intel Core i7-12700','AMD Ryzen 7 7800X3D'],gpu:['NVIDIA GeForce RTX 2060 SUPER','AMD Radeon RX 5700 XT','Intel Arc A770'],ram:16},high:{cpu:['Intel Core i9-12900K','AMD Ryzen 9 7900X'],gpu:['NVIDIA GeForce RTX 3080','AMD Radeon RX 7900 XTX'],ram:20,label:'Ultra（4K）'},disk:70,ssd:'req',note:'官方要求 SSD。最低＝1080p 低畫質 30fps、建議＝1080p 高畫質 60fps。'}},
  {id:'mhwilds',n:'魔物獵人 荒野',en:'Monster Hunter Wilds',cat:'單機大作／動作 RPG',verified:false,upd:'2025（修訂版需求）',src:'https://store.steampowered.com/app/2246340/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-10400','Intel Core i3-12100F','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce GTX 1660 SUPER','AMD Radeon RX 5600 XT','Intel Arc A580'],ram:16},rec:{cpu:['Intel Core i5-11600K','Intel Core i5-12400','AMD Ryzen 5 3600X','AMD Ryzen 5 5500'],gpu:['NVIDIA GeForce RTX 2070 SUPER','NVIDIA GeForce RTX 4060','AMD Radeon RX 6600 XT'],ram:16},disk:75,ssd:'req',note:'官方要求 SSD。最低＝1080p（升頻）低畫質 30fps；建議＝1080p 中畫質 60fps（含畫格生成）。'}},
  {id:'gta5',n:'俠盜獵車手 V（Legacy）',en:'Grand Theft Auto V',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://www.rockstargames.com/gta-v',srcName:'Rockstar 官方',
   pc:{os:'win10',min:{cpu:['Intel Core 2 Quad Q6600','AMD Phenom 9850'],gpu:['NVIDIA GeForce 9800 GT','AMD Radeon HD 4870'],ram:4},rec:{cpu:['Intel Core i5-3470','AMD FX-8350'],gpu:['NVIDIA GeForce GTX 660','AMD Radeon HD 7870'],ram:8},disk:110,note:'Enhanced 版本另需 RTX 2060／RX 5600 XT 以上。'}},
  {id:'rdr2',n:'碧血狂殺 2',en:'Red Dead Redemption 2',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1174180/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-2500K','AMD FX-6300'],gpu:['NVIDIA GeForce GTX 770','AMD Radeon R9 280'],ram:8},rec:{cpu:['Intel Core i7-4770K','AMD Ryzen 5 1500X'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 480'],ram:12},disk:150,ssd:'rec'}},
  {id:'witcher3',n:'巫師 3：狂獵（次世代版）',en:'The Witcher 3: Wild Hunt',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/292030/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-7400','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:8},rec:{cpu:['Intel Core i7-8700K','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce RTX 2060','AMD Radeon RX 6600 XT'],ram:16},disk:50,ssd:'rec',note:'次世代版需求；光追需 RTX 3070／RX 6700 XT 以上。'}},
  {id:'hogwarts',n:'霍格華茲的傳承',en:'Hogwarts Legacy',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/990080/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-6600','AMD Ryzen 5 1400'],gpu:['NVIDIA GeForce GTX 960','AMD Radeon RX 470'],ram:16},rec:{cpu:['Intel Core i7-8700','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce GTX 1080 Ti','AMD Radeon RX 5700 XT'],ram:16},disk:85,ssd:'req'}},
  {id:'re4',n:'惡靈古堡 4（重製版）',en:'Resident Evil 4',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2050650/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-7500','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 1050 Ti','AMD Radeon RX 560'],ram:8},rec:{cpu:['Intel Core i7-8700','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce GTX 1070','AMD Radeon RX 5700'],ram:16},disk:60,ssd:'rec'}},
  {id:'requiem',n:'惡靈古堡 安魂曲',en:'Resident Evil Requiem',cat:'單機大作／動作 RPG',verified:true,upd:'2026-02',src:'https://store.steampowered.com/app/3646370/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-8500','AMD Ryzen 5 3500'],gpu:['NVIDIA GeForce GTX 1660','AMD Radeon RX 5500 XT'],ram:16},rec:{cpu:['Intel Core i7-8700','AMD Ryzen 5 5500'],gpu:['NVIDIA GeForce RTX 2060 SUPER','AMD Radeon RX 6600'],ram:16},disk:75,ssd:'req',note:'DirectX 12；顯示記憶體至少 6GB。最低對應 1080p（升頻）30fps，建議對應 1080p 60fps。'}},
  {id:'sh2',n:'沉默之丘 2（重製版）',en:'Silent Hill 2',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2124490/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i7-6700K','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce GTX 1080','AMD Radeon RX 5700'],ram:16},rec:{cpu:['Intel Core i7-8700K','AMD Ryzen 7 3700X'],gpu:['NVIDIA GeForce RTX 2080','AMD Radeon RX 6800 XT'],ram:16},disk:50,ssd:'req'}},
  {id:'spiderman2',n:'漫威蜘蛛人 2',en:"Marvel's Spider-Man 2",cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2651280/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-8400','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce GTX 1650','AMD Radeon RX 5500 XT'],ram:16},rec:{cpu:['Intel Core i5-11400','AMD Ryzen 5 5600'],gpu:['NVIDIA GeForce RTX 3060','AMD Radeon RX 5700 XT'],ram:16},disk:150,ssd:'req'}},
  {id:'gowr',n:'戰神：諸神黃昏',en:'God of War Ragnarök',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2322010/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-4670K','AMD Ryzen 5 1500X'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 5500 XT'],ram:8},rec:{cpu:['Intel Core i5-8600','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce RTX 2060 SUPER','AMD Radeon RX 5700'],ram:16},disk:190,ssd:'req'}},
  {id:'hfw',n:'地平線 西域禁地',en:'Horizon Forbidden West',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2420110/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i3-8100','AMD Ryzen 3 1300X'],gpu:['NVIDIA GeForce GTX 1650','AMD Radeon RX 5500 XT'],ram:16},rec:{cpu:['Intel Core i5-8600','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce RTX 3060','AMD Radeon RX 5700'],ram:16},disk:150,ssd:'req'}},
  {id:'got',n:'對馬戰鬼',en:'Ghost of Tsushima',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2215430/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i3-7100','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 960','AMD Radeon RX 5500 XT'],ram:8},rec:{cpu:['Intel Core i5-8600','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce RTX 2060','AMD Radeon RX 5600 XT'],ram:16},disk:75,ssd:'req'}},
  {id:'ffxvi',n:'Final Fantasy XVI',en:'Final Fantasy XVI',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2515020/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-8400','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1070','AMD Radeon RX 5700'],ram:16},rec:{cpu:['Intel Core i7-8700K','AMD Ryzen 7 3700X'],gpu:['NVIDIA GeForce RTX 2080','AMD Radeon RX 6800 XT'],ram:16},disk:170,ssd:'req'}},
  {id:'sekiro',n:'隻狼：暗影雙死',en:'Sekiro: Shadows Die Twice',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/814380/',srcName:'Steam 商店頁',
   pc:{os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-6300'],gpu:['NVIDIA GeForce GTX 760','AMD Radeon HD 7950'],ram:4},rec:{cpu:['Intel Core i5-2500K','AMD Ryzen 5 1400'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon RX 570'],ram:8},disk:25}},
  {id:'ds3',n:'黑暗靈魂 3',en:'Dark Souls III',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/374320/',srcName:'Steam 商店頁',
   pc:{os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-6300'],gpu:['NVIDIA GeForce GTX 750 Ti','AMD Radeon R7 265'],ram:8},rec:{cpu:['Intel Core i7-3770','AMD FX-8350'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon R9 380'],ram:8},disk:25}},
  {id:'liesofp',n:'P 的謊言',en:'Lies of P',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1627720/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-7500','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 1050 Ti','AMD Radeon RX 560'],ram:8,est:true},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GTX 1660','AMD Radeon RX 580'],ram:16,est:true},disk:50,ssd:'rec'}},
  {id:'doomtda',n:'毀滅戰士：黑暗時代',en:'DOOM: The Dark Ages',cat:'單機大作／動作 RPG',verified:false,upd:'2025-05',src:'https://store.steampowered.com/app/3017860/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i7-8700K','AMD Ryzen 7 3700X'],gpu:['NVIDIA GeForce RTX 2060 SUPER','AMD Radeon RX 6600'],ram:16},rec:{cpu:['Intel Core i7-12700K','AMD Ryzen 7 5800X'],gpu:['NVIDIA GeForce RTX 3080','AMD Radeon RX 6800'],ram:32,est:true},disk:100,ssd:'req',note:'需支援光追的顯示卡（顯示記憶體 8GB 以上）。'}},
  {id:'kcd2',n:'天國降臨：救贖 2',en:'Kingdom Come: Deliverance II',cat:'單機大作／動作 RPG',verified:false,upd:'2025-02',src:'https://store.steampowered.com/app/1771300/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:16},rec:{cpu:['Intel Core i7-13700K','AMD Ryzen 7 7800X3D'],gpu:['NVIDIA GeForce RTX 4070','AMD Radeon RX 7800 XT'],ram:32},disk:100,ssd:'req'}},
  {id:'exp33',n:'光與影：33 號遠征隊',en:'Clair Obscur: Expedition 33',cat:'單機大作／動作 RPG',verified:false,upd:'2025-04',src:'https://store.steampowered.com/app/1903340/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i7-8700K','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 5600 XT'],ram:8},rec:{cpu:['Intel Core i7-8700K','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce RTX 2060','AMD Radeon RX 5700 XT'],ram:16},disk:55,ssd:'req'}},
  {id:'acshadows',n:'刺客教條：暗影者',en:"Assassin's Creed Shadows",cat:'單機大作／動作 RPG',verified:false,upd:'2025-03',src:'https://store.steampowered.com/app/3159330/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i7-8700K','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce GTX 1070','AMD Radeon RX 5700','Intel Arc A580'],ram:16},rec:{cpu:['Intel Core i5-11600K','AMD Ryzen 5 5600X'],gpu:['NVIDIA GeForce RTX 3060 Ti','AMD Radeon RX 6700 XT','Intel Arc B580'],ram:16},disk:100,ssd:'req'}},
  {id:'silksong',n:'空洞騎士：絲之歌',en:'Hollow Knight: Silksong',cat:'單機大作／動作 RPG',verified:true,upd:'2025-09',src:'https://store.steampowered.com/app/1030300/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i3-3240','AMD FX-4300'],gpu:['NVIDIA GeForce GTX 560 Ti','AMD Radeon HD 7750'],ram:4},rec:{cpu:['Intel Core i5-3470'],gpu:['NVIDIA GeForce GTX 1050','AMD Radeon R9 380'],ram:8},disk:8,note:'需 Windows 10 21H1 以上。'}},
  {id:'hades2',n:'黑帝斯 II',en:'Hades II',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1145350/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-3470','AMD FX-8350'],gpu:['NVIDIA GeForce GTX 960','AMD Radeon RX 470'],ram:8,est:true},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:8,est:true},disk:10}},
  {id:'ninesols',n:'九日',en:'Nine Sols',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1809540/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-4460','AMD FX-6300'],gpu:['NVIDIA GeForce GTX 750 Ti','AMD Radeon R7 260X'],ram:4,est:true},rec:{cpu:['Intel Core i5-6500','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 1050','AMD Radeon RX 560'],ram:8,est:true},disk:8}},
  {id:'mhworld',n:'魔物獵人 世界',en:'Monster Hunter: World',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/582010/',srcName:'Steam 商店頁',
   pc:{os:'win7',min:{cpu:['Intel Core i5-4460','AMD FX-6300'],gpu:['NVIDIA GeForce GTX 760','AMD Radeon R7 260X'],ram:8},rec:{cpu:['Intel Core i7-3770','AMD Ryzen 5 1500X'],gpu:['NVIDIA GeForce GTX 1060 3GB','AMD Radeon RX 570'],ram:8},disk:52,ssd:'rec'}},
  {id:'bg3',n:'柏德之門 3',en:"Baldur's Gate 3",cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1086940/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-4690','AMD FX-8350'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon RX 480'],ram:8},rec:{cpu:['Intel Core i7-8700K','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce RTX 2060 SUPER','AMD Radeon RX 5700 XT'],ram:16},disk:150,ssd:'req'}},
  {id:'schedule1',n:'Schedule I',en:'Schedule I',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/3164500/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-4460','AMD FX-8350'],gpu:['NVIDIA GeForce GTX 960','AMD Radeon RX 560'],ram:8,est:true},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:16,est:true},disk:10}},
  {id:'spacemarine2',n:'戰鎚 40K：星際戰士 2',en:'Warhammer 40,000: Space Marine 2',cat:'單機大作／動作 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2183900/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-8600K','AMD Ryzen 5 2600X'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:8},rec:{cpu:['Intel Core i7-12700','AMD Ryzen 7 5800X'],gpu:['NVIDIA GeForce RTX 3070','AMD Radeon RX 6800'],ram:16,est:true},disk:75,ssd:'req'}},

  // ══════════ MMORPG／線上 RPG ══════════
  {id:'diablo4',n:'暗黑破壞神 IV',en:'Diablo IV',cat:'MMORPG／線上 RPG',verified:false,upd:'2025',src:'https://diablo4.blizzard.com/',srcName:'Blizzard 官方',
   pc:{os:'win10',min:{cpu:['Intel Core i5-2500K','AMD FX-8350'],gpu:['NVIDIA GeForce GTX 660','AMD Radeon R9 280'],ram:8},rec:{cpu:['Intel Core i5-4670K','AMD Ryzen 3 1300X'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon RX 470'],ram:16},disk:90,ssd:'req',note:'DirectX 12，官方要求 SSD。'}},
  {id:'wow',n:'魔獸世界',en:'World of Warcraft',cat:'MMORPG／線上 RPG',verified:false,upd:'2024（地心之戰）',src:'https://worldofwarcraft.blizzard.com/',srcName:'Blizzard 官方',
   pc:{os:'win10',min:{cpu:['Intel Core i5-3450','AMD FX-8300'],gpu:['NVIDIA GeForce GTX 760','AMD Radeon RX 560','Intel UHD Graphics 630'],ram:8},rec:{cpu:['Intel Core i7-6700K','AMD Ryzen 7 2700X'],gpu:['NVIDIA GeForce GTX 1080','AMD Radeon RX Vega 64','Intel Arc A750'],ram:16},disk:128,ssd:'req',note:'官方要求 SSD。新資料片可能再提高需求。'}},
  {id:'ffxiv',n:'Final Fantasy XIV（黃金的遺產）',en:'FINAL FANTASY XIV: Dawntrail',cat:'MMORPG／線上 RPG',verified:false,upd:'2024-07',src:'https://www.finalfantasyxiv.com/',srcName:'Square Enix 官方',
   pc:{os:'win10',min:{cpu:['Intel Core i7-7700'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon RX 480'],ram:8},rec:{cpu:['Intel Core i7-9700'],gpu:['NVIDIA GeForce RTX 2060','AMD Radeon RX 5600 XT'],ram:16},disk:140,ssd:'rec',note:'官方 CPU 僅列 Intel，AMD 同等級即可。'}},
  {id:'lostark',n:'失落的方舟',en:'Lost Ark',cat:'MMORPG／線上 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1599340/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i3（泛指）','AMD Ryzen 3（泛指）'],gpu:['NVIDIA GeForce GTX 460','AMD Radeon HD 6850'],ram:8},rec:{cpu:['Intel Core i5（泛指）','AMD Ryzen 5（泛指）'],gpu:['NVIDIA GeForce GTX 1050','AMD Radeon RX 550'],ram:16},disk:50,note:'DirectX 9 以上；官方建議顯卡為 RX 540（以 RX 550 近似）。'}},
  {id:'starres',n:'星痕共鳴',en:'Blue Protocol: Star Resonance',cat:'MMORPG／線上 RPG',verified:true,upd:'2025-07（手機需求）',src:'https://bpsr.pde.tw/',srcName:'官方公告（Android 需求）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-4150','AMD FX-6300'],gpu:['Intel HD Graphics 4000','NVIDIA GeForce GT 730'],ram:4},rec:{cpu:['Intel Core i5-6500','AMD Ryzen 5 1400'],gpu:['NVIDIA GeForce GTX 1050','AMD Radeon RX 560'],ram:8,est:true},disk:10,ssd:'rec',note:'台灣版目前為手機平台，PC 可用 MuMu、BlueStacks 等模擬器遊玩，以上為模擬器需求（需開啟虛擬化 VT）。建議欄為估算。'},
   android:{min:{soc:['Snapdragon 768G','Dimensity 820','Kirin 820','Exynos 9825'],ram:6},rec:{soc:['Snapdragon 888','Dimensity 8200','Kirin 9000s','Exynos 2100'],ram:8},disk:20},
   ios:{min:{chip:'Apple A13 Bionic',ram:4,os:14,est:true},rec:{chip:'Apple A15 Bionic',ram:6,est:true},disk:20}},
  {id:'poe2',n:'流亡黯道 2',en:'Path of Exile 2',cat:'MMORPG／線上 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2694490/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i7-4790K','AMD Ryzen 5 1500X'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 480'],ram:16,est:true},rec:{cpu:['Intel Core i7-8700K','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce RTX 2070','AMD Radeon RX 5700 XT'],ram:16,est:true},disk:100,ssd:'req'}},
  {id:'lastepoch',n:'Last Epoch',en:'Last Epoch',cat:'MMORPG／線上 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/899770/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-2500','AMD FX-4350'],gpu:['NVIDIA GeForce GTX 660','AMD Radeon R7 370'],ram:8,est:true},rec:{cpu:['Intel Core i5-6500','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:16,est:true},disk:20,ssd:'rec'}},
  {id:'bdo',n:'黑色沙漠',en:'Black Desert',cat:'MMORPG／線上 RPG',verified:false,upd:'2025',src:'https://www.tw.playblackdesert.com/',srcName:'Pearl Abyss 官方（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i3-530','AMD FX-4100'],gpu:['NVIDIA GeForce GTX 650','AMD Radeon HD 7770'],ram:8,est:true},rec:{cpu:['Intel Core i5-6600','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon R9 380'],ram:16,est:true},disk:60,ssd:'rec'},
   android:{min:{soc:['Snapdragon 660'],ram:3,os:7,est:true},rec:{soc:['Snapdragon 855'],ram:6,est:true},disk:10},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:13,est:true},rec:{chip:'Apple A13 Bionic',ram:4,est:true},disk:10}},
  {id:'newworld',n:'新世界：永恆之境',en:'New World: Aeternum',cat:'MMORPG／線上 RPG',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1063730/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-2400','AMD Ryzen 5 1400'],gpu:['NVIDIA GeForce GTX 670','AMD Radeon RX 460'],ram:8,est:true},rec:{cpu:['Intel Core i7-2600K','AMD Ryzen 5 1500X'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon R9 290'],ram:16,est:true},disk:50,ssd:'rec'}},
  {id:'maplestory',n:'新楓之谷',en:'MapleStory',cat:'MMORPG／線上 RPG',verified:false,upd:'2025',src:'https://maplestory.beanfun.com/',srcName:'beanfun 官方（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i3（泛指）'],gpu:['Intel HD Graphics 4000'],ram:4,est:true},rec:{cpu:['Intel Core i5（泛指）'],gpu:['NVIDIA GeForce GTX 1050'],ram:8,est:true},disk:30,ssd:'rec'}},
  {id:'hearthstone',n:'爐石戰記',en:'Hearthstone',cat:'MMORPG／線上 RPG',verified:false,upd:'2025',src:'https://hearthstone.blizzard.com/',srcName:'Blizzard 官方',
   pc:{os:'win10',min:{cpu:['Intel Pentium D 820','AMD Athlon 64 X2'],gpu:['NVIDIA GeForce 8600 GT','Intel HD Graphics 3000'],ram:3},rec:{cpu:['Intel Core i3（泛指）'],gpu:['Intel HD Graphics 4000'],ram:4,est:true},disk:3},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:7,est:true},rec:{soc:['Snapdragon 660'],ram:3,est:true},disk:3},
   ios:{min:{chip:'Apple A9',ram:2,os:13,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:3}},
  {id:'diabloimmortal',n:'暗黑破壞神：永生不朽',en:'Diablo Immortal',cat:'MMORPG／線上 RPG',verified:false,upd:'2025',src:'https://diabloimmortal.blizzard.com/',srcName:'Blizzard 官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i3（泛指）','AMD FX-8100'],gpu:['NVIDIA GeForce GTX 460','AMD Radeon HD 6850','Intel HD Graphics 530'],ram:8},rec:{cpu:['Intel Core i5-4670K','AMD FX-8350'],gpu:['NVIDIA GeForce GTX 770','AMD Radeon RX 470'],ram:8,est:true},disk:24,ssd:'rec'},
   android:{min:{soc:['Snapdragon 660','Exynos 9611'],ram:2,os:5},rec:{soc:['Snapdragon 855'],ram:4,est:true},disk:15},
   ios:{min:{chip:'Apple A11 Bionic',ram:2,os:11},rec:{chip:'Apple A13 Bionic',ram:4,est:true},disk:15,note:'最低 iPhone 8。'}},

  // ══════════ 沙盒／休閒／派對 ══════════
  {id:'mcjava',n:'Minecraft（Java 版）',en:'Minecraft: Java Edition',cat:'沙盒／休閒／派對',verified:false,upd:'2025',src:'https://help.minecraft.net/',srcName:'Minecraft 官方說明',
   pc:{os:'win10',min:{cpu:['Intel Core i3-3210','AMD A8-7600'],gpu:['Intel HD Graphics 4000','GeForce 400 系列 / Radeon HD 7000 系列（泛指，OpenGL 4.4）'],ram:4},rec:{cpu:['Intel Core i5-4690','AMD A10-7800'],gpu:['GeForce 700 系列 / Radeon Rx 200 系列（泛指，OpenGL 4.5）'],ram:8},disk:4,ssd:'rec',note:'需 OpenGL 4.4 以上；光影／模組包需求會高很多。'}},
  {id:'mcbedrock',n:'Minecraft（基岩版，手機）',en:'Minecraft: Bedrock Edition',cat:'沙盒／休閒／派對',verified:false,upd:'2025',src:'https://help.minecraft.net/',srcName:'Minecraft 官方說明',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i3-3210','AMD A8-7600'],gpu:['Intel HD Graphics 4000','AMD Radeon Vega 8'],ram:4},rec:{cpu:['Intel Core i5-4690','AMD A10-7800'],gpu:['GeForce 700 系列 / Radeon Rx 200 系列（泛指，OpenGL 4.5）'],ram:8},disk:4,note:'Windows 版 Minecraft（基岩版）需求，與 Java 版相同；需 Windows 10／11。'},
   android:{min:{soc:['Snapdragon 450'],ram:2,os:8,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:2,note:'需 Android 8 以上。'},
   ios:{min:{chip:'Apple A9',ram:2,os:15,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:2}},
  {id:'roblox',n:'Roblox',en:'Roblox',cat:'沙盒／休閒／派對',verified:false,upd:'2025',src:'https://en.help.roblox.com/',srcName:'Roblox 官方說明',
   pc:{os:'win10',min:{cpu:['1.6GHz 處理器（泛指）'],gpu:['DirectX 10 相容顯示卡（泛指）'],ram:1},rec:{cpu:['Intel Core i3-6100'],gpu:['NVIDIA GeForce GTX 750 Ti'],ram:8,est:true},disk:2,note:'官方僅列最低（1.6GHz CPU、1GB RAM、DirectX 10）；建議配備為估算。'},
   android:{min:{soc:['Snapdragon 450'],ram:2,os:7,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:2},
   ios:{min:{chip:'Apple A9',ram:2,os:15,est:true},rec:{chip:'Apple A12 Bionic',ram:3,est:true},disk:2}},
  {id:'balatro',n:'Balatro',en:'Balatro',cat:'沙盒／休閒／派對',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2379780/',srcName:'Steam 商店頁',
   pc:{os:'win7',min:{cpu:['1.6GHz 處理器（泛指）'],gpu:['DirectX 10 相容顯示卡（泛指）'],ram:1},rec:{cpu:['雙核心 2.8GHz 處理器（泛指）'],gpu:['Intel HD Graphics 4000'],ram:2,est:true},disk:1},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:8,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:1},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:15,est:true},rec:{chip:'Apple A12 Bionic',ram:3,est:true},disk:1}},
  {id:'stardew',n:'星露谷物語',en:'Stardew Valley',cat:'沙盒／休閒／派對',verified:false,upd:'2025',src:'https://store.steampowered.com/app/413150/',srcName:'Steam 商店頁',
   pc:{os:'win7',min:{cpu:['1.6GHz 處理器（泛指）'],gpu:['DirectX 10 相容顯示卡（泛指）'],ram:2},rec:{cpu:['Intel Core i3（泛指）'],gpu:['Intel HD Graphics 4000'],ram:4,est:true},disk:1},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:6,est:true},rec:{soc:['Snapdragon 660'],ram:3,est:true},disk:1},
   ios:{min:{chip:'Apple A9',ram:2,os:12,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:1}},
  {id:'terraria',n:'Terraria',en:'Terraria',cat:'沙盒／休閒／派對',verified:false,upd:'2025',src:'https://store.steampowered.com/app/105600/',srcName:'Steam 商店頁',
   pc:{os:'win7',min:{cpu:['1.6GHz 處理器（泛指）'],gpu:['DirectX 10 相容顯示卡（泛指）'],ram:3},rec:{cpu:['Intel Core i3（泛指）'],gpu:['Intel HD Graphics 4000'],ram:4},disk:1},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:7,est:true},rec:{soc:['Snapdragon 660'],ram:3,est:true},disk:1},
   ios:{min:{chip:'Apple A9',ram:2,os:12,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:1}},

  // ══════════ 手機遊戲：射擊／競技 ══════════
  {id:'idv',n:'第五人格',en:'Identity V',cat:'手機遊戲：射擊／競技',verified:true,upd:'官方資料（2018）＋整理',src:'https://id5.163.com/',srcName:'網易官方（配備資料較舊）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win7',min:{cpu:['Intel Core i3-530'],gpu:['NVIDIA GeForce GT 730','AMD Radeon HD 7570'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 1050','AMD Radeon RX 560'],ram:8,est:true},disk:20,ssd:'rec',note:'官方 PC 互通版（帳號與手機互通，配對池與模擬器玩家相同）。官方只註明 64 位元 Win7 以上、建議獨立顯示卡（內顯可能無法啟動）；最低欄依公開整理、建議欄為估算。'},
   android:{min:{soc:['Snapdragon 652'],ram:1,os:4},rec:{soc:['Snapdragon 820'],ram:4,est:true},disk:8,note:'官方最低 Android 4.2、1GB RAM，實際 2GB 以上才較穩；Snapdragon 652 約 20～30fps，820／650 級 2GB 以上可順暢。'},
   ios:{min:{chip:'Apple A9',ram:2},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:8,note:'官方最低 iPhone 6s。'}},
  {id:'pubgm',n:'PUBG Mobile',en:'PUBG Mobile',cat:'手機遊戲：射擊／競技',verified:false,upd:'2025',src:'https://www.pubgmobile.com/',srcName:'官方',
   pc:{via:'GameLoop 模擬器（騰訊官方）',viaKind:'emu',os:'win7',min:{cpu:['雙核心 2.8GHz 處理器（泛指）'],gpu:['NVIDIA GeForce 8600 GT','Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i3-530','AMD Phenom II X4 955'],gpu:['NVIDIA GeForce GTX 460','AMD Radeon HD 5870'],ram:8,est:true},disk:10,ssd:'rec',note:'PC 是透過 GameLoop（騰訊官方 Android 模擬器）遊玩，以上為模擬器需求；需在 BIOS 開啟虛擬化（VT-x／AMD-V）。實際 3D 手遊要順跑，建議至少 GTX 1050 等級顯示卡。'},
   android:{min:{soc:['Snapdragon 450'],ram:3,os:6,est:true},rec:{soc:['Snapdragon 855'],ram:6,est:true},disk:10,note:'官方最低 Android 5.1.1、2GB RAM（實際 3GB 以上較穩）。'},
   ios:{min:{chip:'Apple A9',ram:2,os:13,est:true},rec:{chip:'Apple A12 Bionic',ram:4,est:true},disk:10}},
  {id:'codm',n:'決勝時刻 Mobile',en:'Call of Duty: Mobile',cat:'手機遊戲：射擊／競技',verified:false,upd:'2025',src:'https://www.callofduty.com/mobile',srcName:'Activision 官方',
   pc:{via:'GameLoop 模擬器（騰訊官方）',viaKind:'emu',os:'win7',min:{cpu:['雙核心 2.8GHz 處理器（泛指）'],gpu:['NVIDIA GeForce 8600 GT','Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i3-530','AMD Phenom II X4 955'],gpu:['NVIDIA GeForce GTX 460','AMD Radeon HD 5870'],ram:8,est:true},disk:10,ssd:'rec',note:'PC 是透過 GameLoop（騰訊官方 Android 模擬器）遊玩，以上為模擬器需求；需在 BIOS 開啟虛擬化（VT-x／AMD-V）。實際 3D 手遊要順跑，建議至少 GTX 1050 等級顯示卡。'},
   android:{min:{soc:['Snapdragon 625'],ram:2,os:6,est:true},rec:{soc:['Snapdragon 855'],ram:6,est:true},disk:8,note:'官方最低 Android 5.1、2GB RAM。'},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:13,est:true},rec:{chip:'Apple A12 Bionic',ram:4,est:true},disk:8}},
  {id:'brawl',n:'荒野亂鬥',en:'Brawl Stars',cat:'手機遊戲：射擊／競技',verified:false,upd:'2025',src:'https://supercell.com/en/games/brawlstars/',srcName:'Supercell 官方',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-4150','AMD FX-6300'],gpu:['Intel HD Graphics 4000','NVIDIA GeForce GT 730'],ram:4},rec:{cpu:['Intel Core i5-6500','AMD Ryzen 5 1400'],gpu:['NVIDIA GeForce GTX 1050','AMD Radeon RX 560'],ram:8,est:true},disk:10,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、Intel／AMD 處理器、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。建議欄為 3D 手遊順跑的估算值。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:6,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:1},
   ios:{min:{chip:'Apple A9',ram:2,os:12,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:1}},
  {id:'freefire',n:'Free Fire',en:'Garena Free Fire',cat:'手機遊戲：射擊／競技',verified:false,upd:'2025',src:'https://ff.garena.com/',srcName:'Garena 官方',
   pc:{via:'Google Play Games（PC 版，Google 官方）',viaKind:'gpg',os:'win10',min:{cpu:['Intel Core i5-6400','AMD Ryzen 3 1200'],gpu:['Intel UHD Graphics 630'],ram:8},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:10,ssd:'req',note:'Free Fire 可在 Google 官方的 Google Play Games（PC）遊玩，也可用 BlueStacks 等模擬器。官方最低：Windows 10（2004）以上、4 核心、Intel UHD 630 等級以上、8GB RAM、SSD、需開啟虛擬化。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:5,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:2,note:'MAX 版需求較高（4GB RAM、約 4GB 空間）。'},
   ios:{min:{chip:'Apple A9',ram:2,os:12,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:2}},
  {id:'knivesout',n:'荒野行動',en:'Knives Out',cat:'手機遊戲：射擊／競技',verified:false,upd:'2025',src:'https://www.knivesout.jp/',srcName:'NetEase 官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win7',min:{cpu:['Intel Core i3-4150'],gpu:['NVIDIA GeForce GT 730'],ram:4,est:true},rec:{cpu:['Intel Core i5-6500'],gpu:['NVIDIA GeForce GTX 1050'],ram:8,est:true},disk:10,note:'有官方 PC 版。'},
   android:{min:{soc:['Snapdragon 636'],ram:3,os:7,est:true},rec:{soc:['Snapdragon 845'],ram:4,est:true},disk:6},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:13,est:true},rec:{chip:'Apple A12 Bionic',ram:4,est:true},disk:6}},
  {id:'arenabreakout',n:'暗區突圍（手機）',en:'Arena Breakout',cat:'手機遊戲：射擊／競技',verified:false,upd:'2025',src:'https://www.arenabreakout.com/',srcName:'Level Infinite 官方（依公開資料整理）',
   pc:{via:'GameLoop 模擬器（騰訊官方）',viaKind:'emu',os:'win7',min:{cpu:['雙核心 2.8GHz 處理器（泛指）'],gpu:['NVIDIA GeForce 8600 GT','Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i3-530','AMD Phenom II X4 955'],gpu:['NVIDIA GeForce GTX 460','AMD Radeon HD 5870'],ram:8,est:true},disk:10,ssd:'rec',note:'PC 玩家可直接玩 Steam 上的《暗區突圍：無限》；手機版也可用 GameLoop 模擬器，以上為模擬器需求（需開啟虛擬化 VT）。'},
   android:{min:{soc:['Snapdragon 660'],ram:4,os:7,est:true},rec:{soc:['Snapdragon 855'],ram:6,est:true},disk:8},
   ios:{min:{chip:'Apple A11 Bionic',ram:3,os:13,est:true},rec:{chip:'Apple A13 Bionic',ram:4,est:true},disk:8}},
  {id:'eggyparty',n:'蛋仔派對',en:'Eggy Party',cat:'手機遊戲：射擊／競技',verified:false,upd:'2025',src:'https://www.eggyparty.com/',srcName:'NetEase 官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-4150','AMD FX-6300'],gpu:['Intel HD Graphics 4000','NVIDIA GeForce GT 730'],ram:4},rec:{cpu:['Intel Core i5-6500','AMD Ryzen 5 1400'],gpu:['NVIDIA GeForce GTX 1050','AMD Radeon RX 560'],ram:8,est:true},disk:10,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、Intel／AMD 處理器、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。建議欄為 3D 手遊順跑的估算值。'},
   android:{min:{soc:['Snapdragon 660'],ram:4,os:7,est:true},rec:{soc:['Snapdragon 855'],ram:6,est:true},disk:6},
   ios:{min:{chip:'Apple A11 Bionic',ram:3,os:13,est:true},rec:{chip:'Apple A13 Bionic',ram:4,est:true},disk:6}},

  // ══════════ 恐怖／合作派對 ══════════
  {id:'dbd',n:'黎明死線',en:'Dead by Daylight',cat:'恐怖／合作派對',verified:false,upd:'2025',src:'https://store.steampowered.com/app/381210/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i3-4170','AMD FX-8120'],gpu:['NVIDIA GeForce GTX 460','AMD Radeon HD 6850'],ram:8},rec:{cpu:['Intel Core i3-4170','AMD FX-8300'],gpu:['NVIDIA GeForce GTX 760','AMD Radeon R7 370'],ram:8},disk:50,ssd:'rec'},
   android:{min:{soc:['Snapdragon 660'],ram:4,os:7,est:true},rec:{soc:['Snapdragon 855'],ram:6,est:true},disk:4},
   ios:{min:{chip:'Apple A11 Bionic',ram:3,os:13,est:true},rec:{chip:'Apple A13 Bionic',ram:4,est:true},disk:4}},
  {id:'phasmo',n:'恐鬼症',en:'Phasmophobia',cat:'恐怖／合作派對',verified:false,upd:'2025',src:'https://store.steampowered.com/app/739630/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-4590','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon R9 390'],ram:8},rec:{cpu:['Intel Core i5-10600','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce RTX 2060','AMD Radeon RX 5700'],ram:16},disk:21,ssd:'rec'}},
  {id:'lethal',n:'致命公司',en:'Lethal Company',cat:'恐怖／合作派對',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1966720/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-7400','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1050 Ti','AMD Radeon RX 560'],ram:8,est:true},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GTX 1650','AMD Radeon RX 570'],ram:8,est:true},disk:3}},
  {id:'repo',n:'R.E.P.O.',en:'R.E.P.O.',cat:'恐怖／合作派對',verified:false,upd:'2025',src:'https://store.steampowered.com/app/3241660/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 960','AMD Radeon RX 560'],ram:8,est:true},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:16,est:true},disk:5}},
  {id:'peak',n:'PEAK',en:'PEAK',cat:'恐怖／合作派對',verified:false,upd:'2025',src:'https://store.steampowered.com/app/3527290/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 960','AMD Radeon RX 560'],ram:8,est:true},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:16,est:true},disk:5}},
  {id:'contentwarning',n:'Content Warning',en:'Content Warning',cat:'恐怖／合作派對',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2881650/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-7400','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1050 Ti','AMD Radeon RX 560'],ram:8,est:true},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GTX 1650','AMD Radeon RX 570'],ram:8,est:true},disk:3}},
  {id:'amongus',n:'Among Us',en:'Among Us',cat:'恐怖／合作派對',verified:false,upd:'2025',src:'https://store.steampowered.com/app/945360/',srcName:'Steam 商店頁',
   pc:{os:'win7',min:{cpu:['1.6GHz 處理器（泛指）'],gpu:['DirectX 10 相容顯示卡（泛指）'],ram:1},rec:{cpu:['雙核心 2.8GHz 處理器（泛指）'],gpu:['Intel HD Graphics 4000'],ram:2,est:true},disk:1},
   android:{min:{soc:['Snapdragon 430'],ram:1,os:6,est:true},rec:{soc:['Snapdragon 625'],ram:2,est:true},disk:1},
   ios:{min:{chip:'Apple A9',ram:2,os:13,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:1}},
  {id:'fallguys',n:'Fall Guys',en:'Fall Guys',cat:'恐怖／合作派對',verified:false,upd:'2025',src:'https://store.epicgames.com/p/fall-guys',srcName:'Epic 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-2300','AMD FX-8100'],gpu:['NVIDIA GeForce GTX 660','AMD Radeon R7 260X'],ram:8,est:true},rec:{cpu:['Intel Core i5-6500','AMD Ryzen 5 1400'],gpu:['NVIDIA GeForce GTX 1050 Ti','AMD Radeon RX 560'],ram:8,est:true},disk:2}},
  {id:'stumble',n:'Stumble Guys',en:'Stumble Guys',cat:'恐怖／合作派對',verified:false,upd:'2025',src:'https://www.stumbleguys.com/',srcName:'Scopely 官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i3（泛指）'],gpu:['Intel HD Graphics 4000'],ram:4,est:true},rec:{cpu:['Intel Core i5（泛指）'],gpu:['NVIDIA GeForce GTX 750 Ti'],ram:8,est:true},disk:2,note:'Steam 官方 PC 版。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:7,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:1},
   ios:{min:{chip:'Apple A9',ram:2,os:12,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:1}},

  // ══════════ 格鬥／運動／賽車 ══════════
  {id:'rocketleague',n:'火箭聯盟',en:'Rocket League',cat:'格鬥／運動／賽車',verified:false,upd:'2025',src:'https://www.rocketleague.com/',srcName:'Psyonix 官方（依公開資料整理）',
   pc:{os:'win7',min:{cpu:['雙核心 2.8GHz 處理器（泛指）'],gpu:['NVIDIA GeForce GTX 760','AMD Radeon R7 265'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 470'],ram:8,est:true},disk:20}},
  {id:'sf6',n:'快打旋風 6',en:'Street Fighter 6',cat:'格鬥／運動／賽車',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1364780/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-7500','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:8},rec:{cpu:['Intel Core i7-8700','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce RTX 2070','AMD Radeon RX 5700 XT'],ram:16},disk:60,ssd:'rec'}},
  {id:'tekken8',n:'鐵拳 8',en:'TEKKEN 8',cat:'格鬥／運動／賽車',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1778820/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-6600K','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1050 Ti','AMD Radeon RX 580'],ram:8},rec:{cpu:['Intel Core i7-7700K','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce RTX 2070','AMD Radeon RX 5700 XT'],ram:16},disk:100,ssd:'req'}},
  {id:'eafc26',n:'EA SPORTS FC 26',en:'EA SPORTS FC 26',cat:'格鬥／運動／賽車',verified:false,upd:'2025-09',src:'https://www.ea.com/games/ea-sports-fc',srcName:'EA 官方（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-6600K','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 1050 Ti','AMD Radeon RX 570'],ram:8},rec:{cpu:['Intel Core i7-6700','AMD Ryzen 7 2700X'],gpu:['NVIDIA GeForce GTX 1660','AMD Radeon RX 5600 XT'],ram:12},disk:100,ssd:'rec'}},
  {id:'fh5',n:'極限競速：地平線 5',en:'Forza Horizon 5',cat:'格鬥／運動／賽車',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1551360/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon RX 470'],ram:8},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 1500X'],gpu:['NVIDIA GeForce GTX 1070','AMD Radeon RX 590'],ram:16},disk:110,ssd:'rec'}},

  // ══════════ 生存／建造／模擬 ══════════
  {id:'palworld',n:'幻獸帕魯',en:'Palworld',cat:'生存／建造／模擬',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1623730/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-3570K'],gpu:['NVIDIA GeForce GTX 1050'],ram:16},rec:{cpu:['Intel Core i9-9900K'],gpu:['NVIDIA GeForce RTX 2070'],ram:32},disk:40,ssd:'rec',note:'官方只列 Intel／NVIDIA，AMD 請對照同等級。'}},
  {id:'valheim',n:'Valheim',en:'Valheim',cat:'生存／建造／模擬',verified:false,upd:'2025',src:'https://store.steampowered.com/app/892970/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['雙核心 2.8GHz 處理器（泛指）'],gpu:['NVIDIA GeForce GTX 950','AMD Radeon R9 290'],ram:8},rec:{cpu:['Intel Core i5（泛指）'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:16},disk:1}},
  {id:'sotf',n:'森林之子',en:'Sons of the Forest',cat:'生存／建造／模擬',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1326470/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-8400','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce GTX 1060 3GB','AMD Radeon RX 570'],ram:12},rec:{cpu:['Intel Core i7-8700K','AMD Ryzen 7 3700X'],gpu:['NVIDIA GeForce RTX 3070','AMD Radeon RX 6800'],ram:16},disk:20,ssd:'rec'}},
  {id:'enshrouded',n:'霧鎖王國',en:'Enshrouded',cat:'生存／建造／模擬',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1203620/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i5-6400','AMD Ryzen 5 2400G'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:16},rec:{cpu:['Intel Core i7-8700','AMD Ryzen 7 3700X'],gpu:['NVIDIA GeForce RTX 3070','AMD Radeon RX 6800'],ram:16},disk:60,ssd:'req'}},
  {id:'arksa',n:'方舟：生存飛升',en:'ARK: Survival Ascended',cat:'生存／建造／模擬',verified:false,upd:'2025',src:'https://store.steampowered.com/app/2399830/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i7-6800K','AMD Ryzen 5 2600X'],gpu:['NVIDIA GeForce GTX 1080','AMD Radeon RX 5600 XT'],ram:16},rec:{cpu:['Intel Core i5-10600K','AMD Ryzen 5 3600X'],gpu:['NVIDIA GeForce RTX 3080','AMD Radeon RX 6800'],ram:32},disk:70,ssd:'req'}},
  {id:'pz',n:'殭屍毀滅工程',en:'Project Zomboid',cat:'生存／建造／模擬',verified:false,upd:'2025',src:'https://store.steampowered.com/app/108600/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i3（泛指）'],gpu:['DirectX 11 相容 1GB 顯示卡（泛指）'],ram:8},rec:{cpu:['Intel Core i5（泛指）'],gpu:['NVIDIA GeForce GTX 1050'],ram:16,est:true},disk:5,note:'官方寫四核心 2.77GHz／2GB 顯示記憶體 OpenGL 2.1。'}},
  {id:'rimworld',n:'RimWorld',en:'RimWorld',cat:'生存／建造／模擬',verified:false,upd:'2025',src:'https://store.steampowered.com/app/294100/',srcName:'Steam 商店頁',
   pc:{os:'win7',min:{cpu:['1.6GHz 處理器（泛指）'],gpu:['Intel HD Graphics 3000'],ram:4},rec:{cpu:['Intel Core i5（泛指）'],gpu:['Intel HD Graphics 4000'],ram:8,est:true},disk:1}},
  {id:'factorio',n:'異星工廠',en:'Factorio',cat:'生存／建造／模擬',verified:false,upd:'2025',src:'https://store.steampowered.com/app/427520/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['雙核心 2.8GHz 處理器（泛指）'],gpu:['DirectX 10 相容顯示卡（泛指）'],ram:4},rec:{cpu:['Intel Core i5（泛指）'],gpu:['DirectX 11 相容 1GB 顯示卡（泛指）'],ram:8},disk:3,note:'官方寫雙核心 3GHz／四核心 3GHz 以上、顯示記憶體 512MB／2GB。'}},
  {id:'satisfactory',n:'Satisfactory',en:'Satisfactory',cat:'生存／建造／模擬',verified:false,upd:'2025',src:'https://store.steampowered.com/app/526870/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-3570','AMD FX-8350'],gpu:['NVIDIA GeForce GTX 770','AMD Radeon RX 470'],ram:8,est:true},rec:{cpu:['Intel Core i7-8700K','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce GTX 1080 Ti','AMD Radeon RX 5700 XT'],ram:16,est:true},disk:20,ssd:'rec'}},
  {id:'dsp',n:'戴森球計畫',en:'Dyson Sphere Program',cat:'生存／建造／模擬',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1366540/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win7',min:{cpu:['Intel Core i3-530','AMD Phenom II X4 955'],gpu:['NVIDIA GeForce GTX 750','AMD Radeon R7 260X'],ram:4,est:true},rec:{cpu:['Intel Core i7-7700K','AMD Ryzen 5 1400'],gpu:['NVIDIA GeForce GTX 1060 6GB','AMD Radeon RX 580'],ram:8,est:true},disk:5}},
  {id:'cities2',n:'大都會：天際 II',en:'Cities: Skylines II',cat:'生存／建造／模擬',verified:false,upd:'2025',src:'https://store.steampowered.com/app/949230/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i7-6700K','AMD Ryzen 5 2600X'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon RX 480'],ram:8},rec:{cpu:['Intel Core i5-12600K','AMD Ryzen 7 5800X'],gpu:['NVIDIA GeForce RTX 3080','AMD Radeon RX 6800 XT'],ram:16},disk:60,ssd:'rec'}},
  {id:'civ7',n:'文明帝國 VII',en:"Sid Meier's Civilization VII",cat:'生存／建造／模擬',verified:false,upd:'2025-02',src:'https://store.steampowered.com/app/1295660/',srcName:'Steam 商店頁',
   pc:{os:'win10',min:{cpu:['Intel Core i3-10100','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GTX 1050','AMD Radeon RX 460','Intel Arc A380'],ram:8},rec:{cpu:['Intel Core i5-10400','AMD Ryzen 5 3600'],gpu:['NVIDIA GeForce RTX 2060','AMD Radeon RX 6600','Intel Arc A750'],ram:16},disk:20,ssd:'rec'}},
  {id:'aoe4',n:'世紀帝國 IV',en:'Age of Empires IV',cat:'生存／建造／模擬',verified:false,upd:'2025',src:'https://store.steampowered.com/app/1466860/',srcName:'Steam 商店頁（依公開資料整理）',
   pc:{os:'win10',min:{cpu:['Intel Core i5-7300U','AMD Ryzen 5 2400G'],gpu:['Intel HD Graphics 520','AMD Radeon Vega 8'],ram:8},rec:{cpu:['Intel Core i5-6600','AMD Ryzen 5 1600'],gpu:['NVIDIA GeForce GTX 970','AMD Radeon RX 570'],ram:16,est:true},disk:50,ssd:'rec'}},

  // ══════════ 手機遊戲：休閒／策略 ══════════
  {id:'marvelsnap',n:'MARVEL SNAP',en:'MARVEL SNAP',cat:'手機遊戲：休閒／策略',verified:false,upd:'2025',src:'https://www.marvelsnap.com/',srcName:'官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i3（泛指）'],gpu:['Intel HD Graphics 4000'],ram:4,est:true},rec:{cpu:['Intel Core i5（泛指）'],gpu:['NVIDIA GeForce GTX 750 Ti'],ram:8,est:true},disk:4,note:'Steam 官方 PC 版。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:7,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:3},
   ios:{min:{chip:'Apple A9',ram:2,os:13,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:3}},
  {id:'pokemongo',n:'Pokémon GO',en:'Pokémon GO',cat:'手機遊戲：休閒／策略',verified:false,upd:'2025',src:'https://pokemongolive.com/',srcName:'Niantic 官方（依公開資料整理）',
   android:{min:{soc:['Snapdragon 450'],ram:2,os:9,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:2,note:'需要 GPS 與相機；Niantic 禁止模擬器，沒有 PC 版。'},
   ios:{min:{chip:'Apple A11 Bionic',ram:2,os:16,est:true},rec:{chip:'Apple A13 Bionic',ram:4,est:true},disk:2}},
  {id:'ptcgp',n:'Pokémon TCG Pocket',en:'Pokémon TCG Pocket',cat:'手機遊戲：休閒／策略',verified:false,upd:'2025',src:'https://tcgpocket.pokemon.com/',srcName:'官方（依公開資料整理）',
   android:{min:{soc:['Snapdragon 450'],ram:3,os:9,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:2},
   ios:{min:{chip:'Apple A11 Bionic',ram:2,os:15,est:true},rec:{chip:'Apple A12 Bionic',ram:3,est:true},disk:2}},
  {id:'coc',n:'部落衝突',en:'Clash of Clans',cat:'手機遊戲：休閒／策略',verified:false,upd:'2025',src:'https://supercell.com/en/games/clashofclans/',srcName:'Supercell 官方（依公開資料整理）',
   pc:{via:'Google Play Games（PC 版，Google 官方）',viaKind:'gpg',os:'win10',min:{cpu:['Intel Core i5-6400','AMD Ryzen 3 1200'],gpu:['Intel UHD Graphics 630'],ram:8},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:10,ssd:'req',note:'PC 是透過 Google 官方的 Google Play Games（PC）遊玩。官方最低：Windows 10（2004）以上、4 個實體核心、Intel UHD 630 等級以上、8GB RAM、SSD 10GB、需開啟硬體虛擬化。建議欄為估算。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:7,est:true},rec:{soc:['Snapdragon 660'],ram:3,est:true},disk:1},
   ios:{min:{chip:'Apple A9',ram:2,os:13,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:1}},
  {id:'clashroyale',n:'皇室戰爭',en:'Clash Royale',cat:'手機遊戲：休閒／策略',verified:false,upd:'2025',src:'https://supercell.com/en/games/clashroyale/',srcName:'Supercell 官方（依公開資料整理）',
   pc:{via:'Google Play Games（PC 版，Google 官方）',viaKind:'gpg',os:'win10',min:{cpu:['Intel Core i5-6400','AMD Ryzen 3 1200'],gpu:['Intel UHD Graphics 630'],ram:8},rec:{cpu:['Intel Core i5-8400','AMD Ryzen 5 2600'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:10,ssd:'req',note:'PC 是透過 Google 官方的 Google Play Games（PC）遊玩。官方最低：Windows 10（2004）以上、4 個實體核心、Intel UHD 630 等級以上、8GB RAM、SSD 10GB、需開啟硬體虛擬化。建議欄為估算。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:7,est:true},rec:{soc:['Snapdragon 660'],ram:3,est:true},disk:1},
   ios:{min:{chip:'Apple A9',ram:2,os:13,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:1}},
  {id:'asphalt',n:'狂野飆車 傳奇集結',en:'Asphalt Legends Unite',cat:'手機遊戲：休閒／策略',verified:false,upd:'2025',src:'https://gameloft.com/game/asphalt-legends',srcName:'Gameloft 官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i3-4150'],gpu:['Intel HD Graphics 4400'],ram:4,est:true},rec:{cpu:['Intel Core i5-6500'],gpu:['NVIDIA GeForce GTX 1050'],ram:8,est:true},disk:8,note:'Steam／Microsoft Store 官方 PC 版。'},
   android:{min:{soc:['Snapdragon 660'],ram:3,os:8,est:true},rec:{soc:['Snapdragon 855'],ram:6,est:true},disk:6},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:14,est:true},rec:{chip:'Apple A13 Bionic',ram:4,est:true},disk:6}},

  // ══════════ 手機遊戲：二次元／RPG ══════════
  {id:'bluearchive',n:'蔚藍檔案',en:'Blue Archive',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://bluearchive.nexon.com/',srcName:'Nexon 官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-4100'],gpu:['Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:8,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。2D／輕量手遊對顯示卡要求很低。'},
   android:{min:{soc:['Snapdragon 625'],ram:3,os:7},rec:{soc:['Snapdragon 730G'],ram:4,est:true},disk:8},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:13,est:true},rec:{chip:'Apple A12 Bionic',ram:3,est:true},disk:8}},
  {id:'arknights',n:'明日方舟',en:'Arknights',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://www.arknights.global/',srcName:'官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-4100'],gpu:['Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:8,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。2D／輕量手遊對顯示卡要求很低。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:5,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:8},
   ios:{min:{chip:'Apple A9',ram:2,os:12,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:8}},
  {id:'umamusume',n:'賽馬娘 Pretty Derby',en:'Umamusume: Pretty Derby',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://umamusume.com/',srcName:'Cygames 官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i3-6100'],gpu:['Intel HD Graphics 530'],ram:8,est:true},rec:{cpu:['Intel Core i5-8400'],gpu:['NVIDIA GeForce GTX 1050'],ram:8,est:true},disk:20,note:'Steam／官方 PC 版。'},
   android:{min:{soc:['Snapdragon 636'],ram:3,os:8,est:true},rec:{soc:['Snapdragon 845'],ram:4,est:true},disk:10},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:14,est:true},rec:{chip:'Apple A12 Bionic',ram:3,est:true},disk:10}},
  {id:'fgo',n:'Fate/Grand Order',en:'Fate/Grand Order',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://www.fate-go.com.tw/',srcName:'官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-4100'],gpu:['Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:8,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。2D／輕量手遊對顯示卡要求很低。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:7,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:6},
   ios:{min:{chip:'Apple A9',ram:2,os:13,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:6}},
  {id:'priconne',n:'超異域公主連結☆Re:Dive',en:'Princess Connect! Re:Dive',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://www.princessconnect.so-net.tw/',srcName:'官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-4100'],gpu:['Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:8,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。2D／輕量手遊對顯示卡要求很低。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:7,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:6},
   ios:{min:{chip:'Apple A9',ram:2,os:13,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:6}},
  {id:'azurlane',n:'碧藍航線',en:'Azur Lane',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://azurlane.yo-star.com/',srcName:'官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-4100'],gpu:['Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:8,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。2D／輕量手遊對顯示卡要求很低。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:5,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:6},
   ios:{min:{chip:'Apple A9',ram:2,os:12,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:6}},
  {id:'epicseven',n:'第七史詩',en:'Epic Seven',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://epic7.smilegatemegaport.com/',srcName:'官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-4100'],gpu:['Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:8,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。2D／輕量手遊對顯示卡要求很低。'},
   android:{min:{soc:['Snapdragon 625'],ram:3,os:7,est:true},rec:{soc:['Snapdragon 730G'],ram:4,est:true},disk:8},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:13,est:true},rec:{chip:'Apple A12 Bionic',ram:3,est:true},disk:8}},
  {id:'onmyoji',n:'陰陽師',en:'Onmyoji',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://onmyoji.tw/',srcName:'NetEase 官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-4100'],gpu:['Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:8,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。2D／輕量手遊對顯示卡要求很低。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:5,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:8},
   ios:{min:{chip:'Apple A9',ram:2,os:12,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:8}},
  {id:'pjsekai',n:'世界計畫 繽紛舞台！feat. 初音未來',en:'Project SEKAI',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://pjsekai.sega.jp/',srcName:'官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-4100'],gpu:['Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:8,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。2D／輕量手遊對顯示卡要求很低。'},
   android:{min:{soc:['Snapdragon 660'],ram:4,os:8,est:true},rec:{soc:['Snapdragon 855'],ram:6,est:true},disk:8},
   ios:{min:{chip:'Apple A11 Bionic',ram:3,os:14,est:true},rec:{chip:'Apple A13 Bionic',ram:4,est:true},disk:8}},
  {id:'lineagew',n:'天堂W',en:'Lineage W',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://lineagew.plaync.com/',srcName:'NCSOFT 官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i5-4460'],gpu:['NVIDIA GeForce GTX 750 Ti'],ram:8,est:true},rec:{cpu:['Intel Core i7-7700'],gpu:['NVIDIA GeForce GTX 1060 6GB'],ram:16,est:true},disk:20,ssd:'rec',note:'PC 透過 NCSOFT 官方 PURPLE 平台遊玩。'},
   android:{min:{soc:['Snapdragon 660'],ram:3,os:7,est:true},rec:{soc:['Snapdragon 855'],ram:6,est:true},disk:10},
   ios:{min:{chip:'Apple A11 Bionic',ram:3,os:13,est:true},rec:{chip:'Apple A13 Bionic',ram:4,est:true},disk:10}},
  {id:'lineagem',n:'天堂M',en:'Lineage M',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://lineagem.beanfun.com/',srcName:'beanfun 官方（依公開資料整理）',
   pc:{via:'官方電腦版',viaKind:'official',os:'win10',min:{cpu:['Intel Core i3-6100'],gpu:['Intel HD Graphics 530'],ram:4,est:true},rec:{cpu:['Intel Core i5-8400'],gpu:['NVIDIA GeForce GTX 1050'],ram:8,est:true},disk:10,note:'PC 透過官方 PURPLE 平台遊玩。'},
   android:{min:{soc:['Snapdragon 625'],ram:3,os:7,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:6},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:13,est:true},rec:{chip:'Apple A12 Bionic',ram:3,est:true},disk:6}},
  {id:'maplestorym',n:'楓之谷M',en:'MapleStory M',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://maplestorym.beanfun.com/',srcName:'beanfun 官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-4100'],gpu:['Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:8,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。2D／輕量手遊對顯示卡要求很低。'},
   android:{min:{soc:['Snapdragon 625'],ram:3,os:7,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:6},
   ios:{min:{chip:'Apple A10 Fusion',ram:2,os:13,est:true},rec:{chip:'Apple A12 Bionic',ram:3,est:true},disk:6}},
  {id:'summonerswar',n:'魔靈召喚',en:'Summoners War',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://summonerswar.com/',srcName:'Com2uS 官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-4100'],gpu:['Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:8,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。2D／輕量手遊對顯示卡要求很低。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:6,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:5},
   ios:{min:{chip:'Apple A9',ram:2,os:12,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:5}},
  {id:'tos',n:'神魔之塔',en:'Tower of Saviors',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://tos.madhead.com/',srcName:'Mad Head 官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-4100'],gpu:['Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:8,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。2D／輕量手遊對顯示卡要求很低。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:6,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:4},
   ios:{min:{chip:'Apple A9',ram:2,os:12,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:4}},
  {id:'monsterstrike',n:'怪物彈珠',en:'Monster Strike',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://www.monster-strike.com.tw/',srcName:'官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-2100','AMD FX-4100'],gpu:['Intel HD Graphics 4000'],ram:4},rec:{cpu:['Intel Core i5-4460','AMD Ryzen 3 1200'],gpu:['NVIDIA GeForce GT 1030','Intel Iris Xe'],ram:8,est:true},disk:8,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。2D／輕量手遊對顯示卡要求很低。'},
   android:{min:{soc:['Snapdragon 430'],ram:2,os:7,est:true},rec:{soc:['Snapdragon 660'],ram:4,est:true},disk:4},
   ios:{min:{chip:'Apple A9',ram:2,os:13,est:true},rec:{chip:'Apple A11 Bionic',ram:3,est:true},disk:4}},
  {id:'bdm',n:'黑色沙漠 MOBILE',en:'Black Desert Mobile',cat:'手機遊戲：二次元／RPG',verified:false,upd:'2025',src:'https://www.tw.blackdesertm.com/',srcName:'Pearl Abyss 官方（依公開資料整理）',
   pc:{via:'Android 模擬器（BlueStacks／LDPlayer／MuMu／夜神）',viaKind:'emu',os:'win7',min:{cpu:['Intel Core i3-4150','AMD FX-6300'],gpu:['Intel HD Graphics 4000','NVIDIA GeForce GT 730'],ram:4},rec:{cpu:['Intel Core i5-6500','AMD Ryzen 5 1400'],gpu:['NVIDIA GeForce GTX 1050','AMD Radeon RX 560'],ram:8,est:true},disk:10,ssd:'rec',note:'沒有官方電腦版，PC 上要用 Android 模擬器（BlueStacks 5 官方最低：Win7 以上、Intel／AMD 處理器、4GB RAM、5GB 空間；建議 Win10、8GB RAM、SSD）；需開啟虛擬化（VT）。建議欄為 3D 手遊順跑的估算值。'},
   android:{min:{soc:['Snapdragon 660'],ram:3,os:7,est:true},rec:{soc:['Snapdragon 855'],ram:6,est:true},disk:10},
   ios:{min:{chip:'Apple A11 Bionic',ram:3,os:13,est:true},rec:{chip:'Apple A13 Bionic',ram:4,est:true},disk:10}},
];
